//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigada_emergencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public brigada_emergencia()
        {
            this.procedimiento_comunicacion = new HashSet<procedimiento_comunicacion>();
        }
    
        public int id_brigada { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string perfiles { get; set; }
        public string func_brigadistas { get; set; }
        public string brigada_comunicacion { get; set; }
        public string dir_emergencia_int { get; set; }
        public string brigada_prim_aux { get; set; }
        public string brigada_incendio { get; set; }
        public string brigada_evacuacion { get; set; }
    
        public virtual sucursal sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procedimiento_comunicacion> procedimiento_comunicacion { get; set; }
    }
}
