//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class claseCiiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public claseCiiu()
        {
            this.empresa_itemdivision = new HashSet<empresa_itemdivision>();
            this.norma_claseciiu = new HashSet<norma_claseciiu>();
            this.riesgos_item = new HashSet<riesgos_item>();
        }
    
        public int id_clase_ciiu { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual grupoCiiu grupoCiiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresa_itemdivision> empresa_itemdivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<norma_claseciiu> norma_claseciiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<riesgos_item> riesgos_item { get; set; }
    }
}
