//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class divisionCiiu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public divisionCiiu()
        {
            this.grupoCiiu = new HashSet<grupoCiiu>();
        }
    
        public int id_division { get; set; }
        public Nullable<int> id_seccion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual seccionCiiu seccionCiiu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<grupoCiiu> grupoCiiu { get; set; }
    }
}
