//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.soporte = new HashSet<soporte>();
        }
    
        public int id_documento { get; set; }
        public Nullable<int> id_tabla { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> fecha_subida { get; set; }
    
        public virtual sucursal sucursal { get; set; }
        public virtual trabajador trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soporte> soporte { get; set; }
    }
}
