//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresa()
        {
            this.categoria = new HashSet<categoria>();
            this.empresa_itemdivision = new HashSet<empresa_itemdivision>();
            this.estatus = new HashSet<estatus>();
            this.horario = new HashSet<horario>();
            this.perfil_cargo = new HashSet<perfil_cargo>();
            this.politica_sst = new HashSet<politica_sst>();
            this.sucursal = new HashSet<sucursal>();
        }
    
        public int id_empresa { get; set; }
        public string nombre { get; set; }
        public string CodEmpresa { get; set; }
        public string nit { get; set; }
        public string email { get; set; }
        public string representante { get; set; }
        public string movil { get; set; }
        public string fijo { get; set; }
        public string logo_url { get; set; }
        public Nullable<int> id_arl { get; set; }
        public Nullable<int> jornada { get; set; }
        public string clase_riesgo { get; set; }
        public string tipo_material { get; set; }
        public string dependencias_adm { get; set; }
        public string dependencias_no_adm { get; set; }
        public Nullable<int> personas_transito { get; set; }
        public string vias_acceso { get; set; }
        public string salida_emergencia { get; set; }
        public string senalizacion { get; set; }
    
        public virtual arl arl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoria> categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empresa_itemdivision> empresa_itemdivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estatus> estatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horario> horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfil_cargo> perfil_cargo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<politica_sst> politica_sst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sucursal> sucursal { get; set; }
    }
}
