//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta_politica
    {
        public int id_encuesta { get; set; }
        public Nullable<int> id_trabajador { get; set; }
        public string ruta { get; set; }
        public Nullable<double> si { get; set; }
        public Nullable<double> no { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
    
        public virtual trabajador trabajador { get; set; }
    }
}
