//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class epp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public epp()
        {
            this.puesto_trabajo_epp = new HashSet<puesto_trabajo_epp>();
        }
    
        public int id_epp { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_tipo_epp { get; set; }
        public string url_imagen { get; set; }
        public string marca_modelo { get; set; }
        public string uso { get; set; }
    
        public virtual tipo_epp tipo_epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puesto_trabajo_epp> puesto_trabajo_epp { get; set; }
    }
}
