//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class factor_identificacion
    {
        public int id_fac_ide { get; set; }
        public Nullable<int> id_factor { get; set; }
        public Nullable<int> id_identificacion { get; set; }
        public string consecuencias { get; set; }
        public string tiempo_exposicion { get; set; }
    
        public virtual factor_riesgo factor_riesgo { get; set; }
        public virtual identificacion_peligro identificacion_peligro { get; set; }
    }
}
