//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public int id_horario { get; set; }
        public string nombre { get; set; }
        public string fecha_inicio { get; set; }
        public string fecha_fin { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
