//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class matriz_responsabilidad
    {
        public int id_matriz_responsabilidad { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public string puesto1 { get; set; }
        public string puesto2 { get; set; }
        public string puesto3 { get; set; }
        public string puesto4 { get; set; }
        public string puesto5 { get; set; }
        public string puesto6 { get; set; }
        public string puesto7 { get; set; }
        public string pusto8 { get; set; }
    
        public virtual sucursal sucursal { get; set; }
    }
}
