//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GrupoLiEntities : DbContext
    {
        public GrupoLiEntities()
            : base("name=GrupoLiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afp> afp { get; set; }
        public virtual DbSet<alarma> alarma { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<arl> arl { get; set; }
        public virtual DbSet<at_it_el_pa> at_it_el_pa { get; set; }
        public virtual DbSet<brigada_emergencia> brigada_emergencia { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<ccf> ccf { get; set; }
        public virtual DbSet<claseCiiu> claseCiiu { get; set; }
        public virtual DbSet<cno> cno { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<desc_socio> desc_socio { get; set; }
        public virtual DbSet<divisionCiiu> divisionCiiu { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<empleo_anterior> empleo_anterior { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<empresa_itemdivision> empresa_itemdivision { get; set; }
        public virtual DbSet<encuesta_politica> encuesta_politica { get; set; }
        public virtual DbSet<enfermedad> enfermedad { get; set; }
        public virtual DbSet<enfermedadLaboral> enfermedadLaboral { get; set; }
        public virtual DbSet<epp> epp { get; set; }
        public virtual DbSet<eps> eps { get; set; }
        public virtual DbSet<estatus> estatus { get; set; }
        public virtual DbSet<evaluacion_riesgo> evaluacion_riesgo { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<extintor> extintor { get; set; }
        public virtual DbSet<factor_identificacion> factor_identificacion { get; set; }
        public virtual DbSet<factor_riesgo> factor_riesgo { get; set; }
        public virtual DbSet<frecuencia_control> frecuencia_control { get; set; }
        public virtual DbSet<gestion_laboral> gestion_laboral { get; set; }
        public virtual DbSet<grupoCiiu> grupoCiiu { get; set; }
        public virtual DbSet<historia_clinica_ocupacional> historia_clinica_ocupacional { get; set; }
        public virtual DbSet<horario> horario { get; set; }
        public virtual DbSet<identificacion_peligro> identificacion_peligro { get; set; }
        public virtual DbSet<identificacion_puesto> identificacion_puesto { get; set; }
        public virtual DbSet<investigacion_ac_in> investigacion_ac_in { get; set; }
        public virtual DbSet<ips> ips { get; set; }
        public virtual DbSet<lista_actividad> lista_actividad { get; set; }
        public virtual DbSet<matriz_responsabilidad> matriz_responsabilidad { get; set; }
        public virtual DbSet<medida> medida { get; set; }
        public virtual DbSet<medida_sucursal> medida_sucursal { get; set; }
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<norma> norma { get; set; }
        public virtual DbSet<norma_claseciiu> norma_claseciiu { get; set; }
        public virtual DbSet<norma_sucursal> norma_sucursal { get; set; }
        public virtual DbSet<obligacion> obligacion { get; set; }
        public virtual DbSet<perfil_cargo> perfil_cargo { get; set; }
        public virtual DbSet<plan> plan { get; set; }
        public virtual DbSet<plan_trabajo> plan_trabajo { get; set; }
        public virtual DbSet<politica_sst> politica_sst { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<procedimiento_comunicacion> procedimiento_comunicacion { get; set; }
        public virtual DbSet<puesto_trabajo> puesto_trabajo { get; set; }
        public virtual DbSet<puesto_trabajo_epp> puesto_trabajo_epp { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<riesgos_item> riesgos_item { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<seccionCiiu> seccionCiiu { get; set; }
        public virtual DbSet<sistema> sistema { get; set; }
        public virtual DbSet<soporte> soporte { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<tipo_epp> tipo_epp { get; set; }
        public virtual DbSet<tipo_evento> tipo_evento { get; set; }
        public virtual DbSet<tipo_examen> tipo_examen { get; set; }
        public virtual DbSet<tipo_riesgo> tipo_riesgo { get; set; }
        public virtual DbSet<trabajador> trabajador { get; set; }
        public virtual DbSet<trabajador_estatus> trabajador_estatus { get; set; }
        public virtual DbSet<trabajador_gestion> trabajador_gestion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<senalizacion> senalizacion { get; set; }
        public virtual DbSet<perfil_medico> perfil_medico { get; set; }
    }
}
