//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class afp
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public afp()
    {
        this.desc_socio = new HashSet<desc_socio>();
    }

    public int id_afp { get; set; }
    public string nombre { get; set; }
    public string codigo { get; set; }
    public string nit { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string ciudad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<desc_socio> desc_socio { get; set; }
}

public partial class alarma
{
    public int id_alarmas { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string prioridad { get; set; }
    public Nullable<int> id_categorias { get; set; }
    public Nullable<int> id_usuario { get; set; }

    public virtual categoria categoria { get; set; }
    public virtual usuario usuario { get; set; }
}

public partial class area
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public area()
    {
        this.at_it_el_pa = new HashSet<at_it_el_pa>();
        this.extintor = new HashSet<extintor>();
        this.puesto_trabajo = new HashSet<puesto_trabajo>();
    }

    public int id_area { get; set; }
    public string nombre { get; set; }
    public int id_sucursal { get; set; }
    public Nullable<long> id_area_padre { get; set; }
    public Nullable<int> nivel { get; set; }
    public string tipo { get; set; }

    public virtual sucursal sucursal { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<at_it_el_pa> at_it_el_pa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<extintor> extintor { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<puesto_trabajo> puesto_trabajo { get; set; }
}

public partial class arl
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public arl()
    {
        this.empresa = new HashSet<empresa>();
    }

    public int id_arl { get; set; }
    public string nombre { get; set; }
    public string codigo { get; set; }
    public string nit { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string ciudad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<empresa> empresa { get; set; }
}

public partial class at_it_el_pa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public at_it_el_pa()
    {
        this.consulta = new HashSet<consulta>();
        this.investigacion_ac_in = new HashSet<investigacion_ac_in>();
        this.soporte = new HashSet<soporte>();
    }

    public int id_at_it_el_pa { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public Nullable<int> id_area { get; set; }
    public Nullable<int> id_puesto { get; set; }
    public string sitio { get; set; }
    public string descripcion { get; set; }
    public string condiciones_inseguras { get; set; }
    public string actos_inseguros { get; set; }
    public string factores_inseguros { get; set; }
    public string factores_personales { get; set; }
    public string reporte_accidente { get; set; }
    public string documento_escaneado { get; set; }
    public string documento_comunicado { get; set; }
    public Nullable<int> num_consultas { get; set; }
    public string frecuencia_consultas { get; set; }
    public string tipo_evento { get; set; }
    public Nullable<System.DateTime> fecha_muerte { get; set; }
    public Nullable<int> dias_incapacidad { get; set; }
    public Nullable<int> dias_cargados { get; set; }
    public Nullable<int> dias_perdidos_ausencia { get; set; }
    public string dias_no_perdidos { get; set; }
    public string tipo_enfermedad { get; set; }
    public Nullable<System.DateTime> fecha_accidente { get; set; }
    public Nullable<System.DateTime> hora_accidente { get; set; }
    public Nullable<int> dias_perdidos_restingido { get; set; }

    public virtual area area { get; set; }
    public virtual puesto_trabajo puesto_trabajo { get; set; }
    public virtual trabajador trabajador { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<consulta> consulta { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<investigacion_ac_in> investigacion_ac_in { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<soporte> soporte { get; set; }
}

public partial class brigada_emergencia
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public brigada_emergencia()
    {
        this.procedimiento_comunicacion = new HashSet<procedimiento_comunicacion>();
    }

    public int id_brigada { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public string perfiles { get; set; }
    public string func_brigadistas { get; set; }
    public string brigada_comunicacion { get; set; }
    public string dir_emergencia_int { get; set; }
    public string brigada_prim_aux { get; set; }
    public string brigada_incendio { get; set; }
    public string brigada_evacuacion { get; set; }

    public virtual sucursal sucursal { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<procedimiento_comunicacion> procedimiento_comunicacion { get; set; }
}

public partial class categoria
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public categoria()
    {
        this.alarma = new HashSet<alarma>();
        this.obligacion = new HashSet<obligacion>();
    }

    public int id_categorias { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public Nullable<int> id_empresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<alarma> alarma { get; set; }
    public virtual empresa empresa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
}

public partial class ccf
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ccf()
    {
        this.trabajador = new HashSet<trabajador>();
    }

    public int id_ccf { get; set; }
    public string nombre { get; set; }
    public string codigo { get; set; }
    public string nit { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string ciudad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador> trabajador { get; set; }
}

public partial class claseCiiu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public claseCiiu()
    {
        this.empresa_itemdivision = new HashSet<empresa_itemdivision>();
        this.norma_claseciiu = new HashSet<norma_claseciiu>();
        this.riesgos_item = new HashSet<riesgos_item>();
    }

    public int id_clase_ciiu { get; set; }
    public Nullable<int> id_grupo { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }

    public virtual grupoCiiu grupoCiiu { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<empresa_itemdivision> empresa_itemdivision { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<norma_claseciiu> norma_claseciiu { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<riesgos_item> riesgos_item { get; set; }
}

public partial class cno
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cno()
    {
        this.perfil_cargo = new HashSet<perfil_cargo>();
    }

    public int id_cno { get; set; }
    public string codigo { get; set; }
    public string ocupacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<perfil_cargo> perfil_cargo { get; set; }
}

public partial class consulta
{
    public int id_consulta { get; set; }
    public int id_acc_lab { get; set; }
    public string tipo { get; set; }
    public string servicio_medico { get; set; }
    public string fecha { get; set; }
    public string medico { get; set; }
    public string diagnostico { get; set; }
    public string sug_trat { get; set; }
    public Nullable<int> id_empresa { get; set; }

    public virtual at_it_el_pa at_it_el_pa { get; set; }
}

public partial class departamento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public departamento()
    {
        this.municipio = new HashSet<municipio>();
    }

    public int id_departamento { get; set; }
    public string nombre { get; set; }
    public Nullable<int> id_region { get; set; }

    public virtual Region Region { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<municipio> municipio { get; set; }
}

public partial class desc_socio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public desc_socio()
    {
        this.empleo_anterior = new HashSet<empleo_anterior>();
    }

    public int id_desc_socio { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public string lugar_nac { get; set; }
    public string nivel_escolaridad { get; set; }
    public string años_aprob { get; set; }
    public string cabeza_fam { get; set; }
    public string num_hijos { get; set; }
    public string repart_resp { get; set; }
    public string menores_dep { get; set; }
    public string cond_social { get; set; }
    public string mot_despl { get; set; }
    public string tipo_vivienda { get; set; }
    public string serv_pub { get; set; }
    public string sist_seg_soc { get; set; }
    public string reg_afiliacion { get; set; }
    public string nivel_sisben { get; set; }
    public Nullable<int> id_eps { get; set; }
    public string afi_sssp { get; set; }
    public Nullable<int> id_afp { get; set; }
    public string afi_riesgo { get; set; }
    public string estrato { get; set; }
    public string vivienda { get; set; }
    public string industria { get; set; }
    public string ruido { get; set; }
    public string contaminacion { get; set; }
    public string descripcion { get; set; }

    public virtual afp afp { get; set; }
    public virtual eps eps { get; set; }
    public virtual trabajador trabajador { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<empleo_anterior> empleo_anterior { get; set; }
}

public partial class divisionCiiu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public divisionCiiu()
    {
        this.grupoCiiu = new HashSet<grupoCiiu>();
    }

    public int id_division { get; set; }
    public Nullable<int> id_seccion { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }

    public virtual seccionCiiu seccionCiiu { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<grupoCiiu> grupoCiiu { get; set; }
}

public partial class documento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public documento()
    {
        this.soporte = new HashSet<soporte>();
    }

    public int id_documento { get; set; }
    public Nullable<int> id_tabla { get; set; }
    public string nombre { get; set; }
    public string ruta { get; set; }
    public string tipo { get; set; }
    public Nullable<System.DateTime> fecha_subida { get; set; }

    public virtual sucursal sucursal { get; set; }
    public virtual trabajador trabajador { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<soporte> soporte { get; set; }
}

public partial class empleo_anterior
{
    public int id_empleos_ant { get; set; }
    public string empresa { get; set; }
    public string area { get; set; }
    public string cargo { get; set; }
    public string años { get; set; }
    public string meses { get; set; }
    public string enfermedades { get; set; }
    public Nullable<int> id_desc_socio { get; set; }

    public virtual desc_socio desc_socio { get; set; }
}

public partial class empresa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public empresa()
    {
        this.categoria = new HashSet<categoria>();
        this.empresa_itemdivision = new HashSet<empresa_itemdivision>();
        this.estatus = new HashSet<estatus>();
        this.horario = new HashSet<horario>();
        this.perfil_cargo = new HashSet<perfil_cargo>();
        this.politica_sst = new HashSet<politica_sst>();
        this.rol = new HashSet<rol>();
        this.sucursal = new HashSet<sucursal>();
    }

    public int id_empresa { get; set; }
    public string nombre { get; set; }
    public string CodEmpresa { get; set; }
    public string nit { get; set; }
    public string email { get; set; }
    public string representante { get; set; }
    public string movil { get; set; }
    public string fijo { get; set; }
    public string logo_url { get; set; }
    public Nullable<int> id_arl { get; set; }
    public Nullable<int> jornada { get; set; }
    public string clase_riesgo { get; set; }
    public string tipo_material { get; set; }
    public string dependencias_adm { get; set; }
    public string dependencias_no_adm { get; set; }
    public Nullable<int> personas_transito { get; set; }
    public string vias_acceso { get; set; }
    public string salida_emergencia { get; set; }
    public string senalizacion { get; set; }

    public virtual arl arl { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<categoria> categoria { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<empresa_itemdivision> empresa_itemdivision { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<estatus> estatus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<horario> horario { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<perfil_cargo> perfil_cargo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<politica_sst> politica_sst { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<rol> rol { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<sucursal> sucursal { get; set; }
}

public partial class empresa_itemdivision
{
    public int id_emp_itemdiv { get; set; }
    public Nullable<int> id_empresa { get; set; }
    public Nullable<int> id_clase_ciiu { get; set; }
    public string num_actividad { get; set; }

    public virtual claseCiiu claseCiiu { get; set; }
    public virtual empresa empresa { get; set; }
}

public partial class encuesta_politica
{
    public int id_encuesta { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public string ruta { get; set; }
    public Nullable<double> si { get; set; }
    public Nullable<double> no { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string tipo { get; set; }

    public virtual trabajador trabajador { get; set; }
}

public partial class enfermedad
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public enfermedad()
    {
        this.trabajador_estatus = new HashSet<trabajador_estatus>();
    }

    public int id_enfermedad { get; set; }
    public Nullable<int> tipo { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_estatus> trabajador_estatus { get; set; }
}

public partial class enfermedadLaboral
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public enfermedadLaboral()
    {
        this.riesgos_item = new HashSet<riesgos_item>();
    }

    public int id_enfermedadLaboral { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<riesgos_item> riesgos_item { get; set; }
}

public partial class epp
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public epp()
    {
        this.puesto_trabajo_epp = new HashSet<puesto_trabajo_epp>();
    }

    public int id_epp { get; set; }
    public string nombre { get; set; }
    public Nullable<int> id_tipo_epp { get; set; }

    public virtual tipo_epp tipo_epp { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<puesto_trabajo_epp> puesto_trabajo_epp { get; set; }
}

public partial class eps
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public eps()
    {
        this.desc_socio = new HashSet<desc_socio>();
    }

    public int id_eps { get; set; }
    public string nombre { get; set; }
    public string codigo { get; set; }
    public string nit { get; set; }
    public string direccion { get; set; }
    public string telefono { get; set; }
    public string ciudad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<desc_socio> desc_socio { get; set; }
}

public partial class estatus
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public estatus()
    {
        this.trabajador_estatus = new HashSet<trabajador_estatus>();
    }

    public int id_estatus { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public Nullable<int> id_empresa { get; set; }

    public virtual empresa empresa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_estatus> trabajador_estatus { get; set; }
}

public partial class evaluacion_riesgo
{
    public int id_evaluacion_riesgo { get; set; }
    public Nullable<int> id_ide_puesto { get; set; }
    public string control_fuente { get; set; }
    public string control_medio { get; set; }
    public string control_individuo { get; set; }
    public Nullable<System.DateTime> fecha_evaluacion { get; set; }
    public string nombre_responsable { get; set; }
    public string estatus_med_fue { get; set; }
    public string estatus_med_amb { get; set; }
    public string estatus_med_trab { get; set; }
    public Nullable<int> porc_estatus { get; set; }
    public string nivel_deficiencia { get; set; }
    public string interpretacion_deficiencia { get; set; }
    public string nivel_exposicion { get; set; }
    public string interpretacion_exposicion { get; set; }
    public string nivel_probabilidad { get; set; }
    public string interpretacion_probabilidad { get; set; }
    public string nivel_consecuencia { get; set; }
    public string nivel_riesgo { get; set; }
    public string interpretacion_nivel_riesgo { get; set; }
    public string aceptabilidad_riesgo { get; set; }
    public Nullable<int> planta { get; set; }
    public Nullable<int> contratistas { get; set; }
    public Nullable<int> visitantes { get; set; }
    public Nullable<int> total { get; set; }
    public string peor_consecuencia { get; set; }
    public string existencia_requisito_legal { get; set; }
    public string eliminación { get; set; }
    public string sustitución { get; set; }
    public string controles_ingenieria { get; set; }
    public string controles_administrativos { get; set; }
    public Nullable<System.DateTime> fecha_ejecucion { get; set; }

    public virtual identificacion_puesto identificacion_puesto { get; set; }
}

public partial class evento
{
    public int id_evento { get; set; }
    public Nullable<System.DateTime> fecha_hora { get; set; }
    public Nullable<int> id_usuario { get; set; }
    public Nullable<int> id_tipo_evento { get; set; }
    public string datos_viejos { get; set; }
    public string datos_nuevos { get; set; }
    public string pagina { get; set; }
    public string tabla { get; set; }

    public virtual tipo_evento tipo_evento { get; set; }
    public virtual usuario usuario { get; set; }
}

public partial class extintor
{
    public int id_extintor { get; set; }
    public string serial_extintor { get; set; }
    public Nullable<System.DateTime> fecha_ultima_recarga { get; set; }
    public Nullable<System.DateTime> fecha_proxima_recarga { get; set; }
    public string peso { get; set; }
    public string presion { get; set; }
    public string tipo_extintor { get; set; }
    public string nombre_empresa { get; set; }
    public Nullable<int> id_area { get; set; }

    public virtual area area { get; set; }
}

public partial class factor_identificacion
{
    public int id_fac_ide { get; set; }
    public Nullable<int> id_factor { get; set; }
    public Nullable<int> id_identificacion { get; set; }
    public string consecuencias { get; set; }
    public string tiempo_exposicion { get; set; }

    public virtual factor_riesgo factor_riesgo { get; set; }
    public virtual identificacion_peligro identificacion_peligro { get; set; }
}

public partial class factor_riesgo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public factor_riesgo()
    {
        this.factor_identificacion = new HashSet<factor_identificacion>();
        this.riesgos_item = new HashSet<riesgos_item>();
    }

    public int id_factor_riesgo { get; set; }
    public string nombre { get; set; }
    public Nullable<int> id_tipo_riesgo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<factor_identificacion> factor_identificacion { get; set; }
    public virtual tipo_riesgo tipo_riesgo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<riesgos_item> riesgos_item { get; set; }
}

public partial class frecuencia_control
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public frecuencia_control()
    {
        this.obligacion = new HashSet<obligacion>();
    }

    public int id_frec_con { get; set; }
    public string nombre { get; set; }
    public Nullable<int> num_Dias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
}

public partial class gestion_laboral
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public gestion_laboral()
    {
        this.trabajador_gestion = new HashSet<trabajador_gestion>();
    }

    public int id_ges_lab { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string descripcion { get; set; }
    public string soporte { get; set; }
    public Nullable<int> tipo_gestion { get; set; }
    public Nullable<int> cant_horas { get; set; }
    public string razon_inasistencia { get; set; }
    public string objetivos { get; set; }
    public Nullable<int> id_usuario { get; set; }

    public virtual usuario usuario { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_gestion> trabajador_gestion { get; set; }
}

public partial class grupoCiiu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public grupoCiiu()
    {
        this.claseCiiu = new HashSet<claseCiiu>();
    }

    public int id_grupo { get; set; }
    public Nullable<int> id_division { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<claseCiiu> claseCiiu { get; set; }
    public virtual divisionCiiu divisionCiiu { get; set; }
}

public partial class historia_clinica_ocupacional
{
    public int id_his_cli_ocu { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public Nullable<int> id_tipo_exa { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string doc_esc_paciente { get; set; }
    public string doc_esc_medico { get; set; }
    public string diagnostico { get; set; }
    public string recomendaciones { get; set; }

    public virtual tipo_examen tipo_examen { get; set; }
    public virtual trabajador trabajador { get; set; }
}

public partial class horario
{
    public int id_horario { get; set; }
    public string nombre { get; set; }
    public string fecha_inicio { get; set; }
    public string fecha_fin { get; set; }
    public Nullable<int> id_empresa { get; set; }
    public Nullable<System.DateTime> fecha_creacion { get; set; }

    public virtual empresa empresa { get; set; }
}

public partial class identificacion_peligro
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public identificacion_peligro()
    {
        this.factor_identificacion = new HashSet<factor_identificacion>();
        this.identificacion_puesto = new HashSet<identificacion_puesto>();
        this.obligacion = new HashSet<obligacion>();
    }

    public int id_identificacion_peligro { get; set; }
    public string medidas_control_existentes { get; set; }
    public string observaciones { get; set; }
    public Nullable<System.DateTime> fecha_identificacion { get; set; }
    public Nullable<int> matriz_riesgo { get; set; }
    public string estatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<factor_identificacion> factor_identificacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<identificacion_puesto> identificacion_puesto { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
}

public partial class identificacion_puesto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public identificacion_puesto()
    {
        this.evaluacion_riesgo = new HashSet<evaluacion_riesgo>();
    }

    public int id_ide_puesto { get; set; }
    public Nullable<int> id_identificacion { get; set; }
    public Nullable<int> id_puesto { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<evaluacion_riesgo> evaluacion_riesgo { get; set; }
    public virtual identificacion_peligro identificacion_peligro { get; set; }
    public virtual puesto_trabajo puesto_trabajo { get; set; }
}

public partial class investigacion_ac_in
{
    public int id_inv_ac_in { get; set; }
    public string tipo { get; set; }
    public Nullable<System.DateTime> fecha_evento { get; set; }
    public Nullable<System.DateTime> hora_evento { get; set; }
    public string dia_semana { get; set; }
    public Nullable<int> antiguedad { get; set; }
    public string actividad_realizaba { get; set; }
    public string naturaleza_lesion { get; set; }
    public string gravedad_lesion { get; set; }
    public string descripcion_lesion { get; set; }
    public string reposo { get; set; }
    public Nullable<int> dias_reposo { get; set; }
    public Nullable<System.DateTime> fecha_reintegro { get; set; }
    public string adiestramiento { get; set; }
    public string costo_transporte { get; set; }
    public string costo_atencion { get; set; }
    public string costo_tratamiento { get; set; }
    public string costo_indemizacion { get; set; }
    public string costo_reemplazo { get; set; }
    public string costo_reposo { get; set; }
    public string costo_materiales { get; set; }
    public string costo_produccion { get; set; }
    public string porque1 { get; set; }
    public string respuesta1 { get; set; }
    public string porque2 { get; set; }
    public string respuesta2 { get; set; }
    public string porque3 { get; set; }
    public string respuesta3 { get; set; }
    public string porque4 { get; set; }
    public string respuesta4 { get; set; }
    public string porque5 { get; set; }
    public string respuesta5 { get; set; }
    public string que { get; set; }
    public string respuesta_que { get; set; }
    public string porque { get; set; }
    public string respuesta_porque { get; set; }
    public string quien { get; set; }
    public string respuesta_quien { get; set; }
    public string donde { get; set; }
    public string respuesta_donde { get; set; }
    public string cuando { get; set; }
    public string respuesta_cuando { get; set; }
    public string como { get; set; }
    public string respuesta_como { get; set; }
    public string cuanto { get; set; }
    public string respuesta_cuanto { get; set; }
    public string tipo_accidente { get; set; }
    public string tipo_lesion { get; set; }
    public string agente_lesion { get; set; }
    public string parte_cuerpo { get; set; }
    public string nota { get; set; }
    public Nullable<int> id_at_it_el_pa { get; set; }
    public string medida1 { get; set; }
    public string responsable1 { get; set; }
    public Nullable<System.DateTime> fecha_medida1 { get; set; }
    public string medida2 { get; set; }
    public string responsable2 { get; set; }
    public Nullable<System.DateTime> fecha_medida2 { get; set; }
    public string medida3 { get; set; }
    public string responsable3 { get; set; }
    public Nullable<System.DateTime> fecha_medida3 { get; set; }
    public string supervisor { get; set; }
    public string tiempo_cargo { get; set; }
    public string actividad { get; set; }

    public virtual at_it_el_pa at_it_el_pa { get; set; }
}

public partial class ips
{
    public int id_ips { get; set; }
    public string beneficiario { get; set; }
    public string estado { get; set; }
    public string nit { get; set; }
}

public partial class lista_actividad
{
    public int id_lista { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public string actividad { get; set; }
    public string estatus { get; set; }
    public Nullable<int> anho { get; set; }
    public string fase { get; set; }
    public string link { get; set; }

    public virtual sucursal sucursal { get; set; }
}

public partial class matriz_responsabilidad
{
    public int id_matriz_responsabilidad { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public string puesto1 { get; set; }
    public string puesto2 { get; set; }
    public string puesto3 { get; set; }
    public string puesto4 { get; set; }
    public string puesto5 { get; set; }
    public string puesto6 { get; set; }
    public string puesto7 { get; set; }
    public string pusto8 { get; set; }

    public virtual sucursal sucursal { get; set; }
}

public partial class medida
{
    public int id_medidas { get; set; }
    public int id_normas { get; set; }
    public string descripcion { get; set; }

    public virtual norma norma { get; set; }
}

public partial class medida_sucursal
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public medida_sucursal()
    {
        this.obligacion = new HashSet<obligacion>();
    }

    public int id_medidas_sucursal { get; set; }
    public Nullable<int> id_normas_sucursal { get; set; }
    public string descripcion { get; set; }
    public Nullable<int> estatus_medida { get; set; }
    public Nullable<int> aplica { get; set; }

    public virtual norma_sucursal norma_sucursal { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
}

public partial class municipio
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public municipio()
    {
        this.sucursal = new HashSet<sucursal>();
        this.trabajador = new HashSet<trabajador>();
    }

    public int id_municipio { get; set; }
    public string nombre { get; set; }
    public int id_departamento { get; set; }

    public virtual departamento departamento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<sucursal> sucursal { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador> trabajador { get; set; }
}

public partial class norma
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public norma()
    {
        this.medida = new HashSet<medida>();
        this.norma_claseciiu = new HashSet<norma_claseciiu>();
        this.norma_sucursal = new HashSet<norma_sucursal>();
    }

    public int id_normas { get; set; }
    public string tipo_matriz { get; set; }
    public string tema_especifico { get; set; }
    public string documento { get; set; }
    public string anho { get; set; }
    public string articulo { get; set; }
    public string literal { get; set; }
    public string paragrafo { get; set; }
    public string numeral { get; set; }
    public string concordante { get; set; }
    public string obligaciones { get; set; }
    public string sanciones { get; set; }
    public Nullable<int> porc_cum { get; set; }
    public string pdf { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<medida> medida { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<norma_claseciiu> norma_claseciiu { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<norma_sucursal> norma_sucursal { get; set; }
}

public partial class norma_claseciiu
{
    public int id_normas_clase { get; set; }
    public Nullable<int> id_normas { get; set; }
    public Nullable<int> id_clase_ciiu { get; set; }

    public virtual claseCiiu claseCiiu { get; set; }
    public virtual norma norma { get; set; }
}

public partial class norma_sucursal
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public norma_sucursal()
    {
        this.medida_sucursal = new HashSet<medida_sucursal>();
    }

    public int id_normas_sucursal { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public Nullable<int> id_normas { get; set; }
    public Nullable<int> estatus_norma { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<medida_sucursal> medida_sucursal { get; set; }
    public virtual norma norma { get; set; }
    public virtual sucursal sucursal { get; set; }
}

public partial class obligacion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public obligacion()
    {
        this.soporte = new HashSet<soporte>();
    }

    public int id_obligacion { get; set; }
    public Nullable<int> id_medida_sucursal { get; set; }
    public Nullable<System.DateTime> fecha_creacion { get; set; }
    public Nullable<System.DateTime> fecha_entrega { get; set; }
    public Nullable<int> id_responsable { get; set; }
    public int id_categorias { get; set; }
    public string prioridad { get; set; }
    public int id_frecuencia_con { get; set; }
    public string descripcion { get; set; }
    public string acciones { get; set; }
    public string estatus_obl { get; set; }
    public Nullable<int> id_identificacion_peligro { get; set; }
    public Nullable<int> id_actividad { get; set; }

    public virtual categoria categoria { get; set; }
    public virtual frecuencia_control frecuencia_control { get; set; }
    public virtual identificacion_peligro identificacion_peligro { get; set; }
    public virtual medida_sucursal medida_sucursal { get; set; }
    public virtual plan_trabajo plan_trabajo { get; set; }
    public virtual usuario usuario { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<soporte> soporte { get; set; }
}

public partial class perfil_cargo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public perfil_cargo()
    {
        this.trabajador = new HashSet<trabajador>();
    }

    public int id_perfil_cargo { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public Nullable<int> id_cno { get; set; }
    public Nullable<int> id_empresa { get; set; }

    public virtual cno cno { get; set; }
    public virtual empresa empresa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador> trabajador { get; set; }
}

public partial class plan
{
    public int id_plan { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public string nombre { get; set; }
    public string tipo { get; set; }

    public virtual sucursal sucursal { get; set; }
}

public partial class plan_trabajo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public plan_trabajo()
    {
        this.obligacion = new HashSet<obligacion>();
    }

    public int id_plan_trabajo { get; set; }
    public string nombre { get; set; }
    public string objetivos { get; set; }
    public Nullable<int> anho { get; set; }
    public Nullable<int> id_responsable { get; set; }
    public Nullable<int> semana_ini { get; set; }
    public Nullable<int> semana_fin { get; set; }
    public Nullable<int> recursos_aprobados { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
    public virtual usuario usuario { get; set; }
}

public partial class politica_sst
{
    public int id_politica { get; set; }
    public Nullable<int> id_empresa { get; set; }
    public Nullable<int> anho { get; set; }
    public string ruta { get; set; }
    public string nombre_archivo { get; set; }
    public string compromiso { get; set; }
    public string objetivos { get; set; }
    public string alcance { get; set; }

    public virtual empresa empresa { get; set; }
}

public partial class Pregunta
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pregunta()
    {
        this.Respuesta = new HashSet<Respuesta>();
    }

    public int id_pregunta { get; set; }
    public string cuerpo_pregunta { get; set; }
    public Nullable<int> id_usuario { get; set; }
    public string titulo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<int> estatus { get; set; }

    public virtual usuario usuario { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Respuesta> Respuesta { get; set; }
}

public partial class procedimiento_comunicacion
{
    public int id_procedimiento { get; set; }
    public Nullable<int> id_brigada { get; set; }
    public string nombre { get; set; }
    public string cargo { get; set; }
    public string num_telefono { get; set; }
    public string llamar { get; set; }

    public virtual brigada_emergencia brigada_emergencia { get; set; }
}

public partial class puesto_trabajo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public puesto_trabajo()
    {
        this.at_it_el_pa = new HashSet<at_it_el_pa>();
        this.identificacion_puesto = new HashSet<identificacion_puesto>();
        this.puesto_trabajo_epp = new HashSet<puesto_trabajo_epp>();
        this.trabajador = new HashSet<trabajador>();
    }

    public int id_puesto_trabajo { get; set; }
    public string nombre { get; set; }
    public int id_area { get; set; }
    public string descripcion { get; set; }
    public string recurso_humano { get; set; }
    public string objeto_trabajo { get; set; }
    public string insumos { get; set; }
    public string maquinas { get; set; }
    public string herramientas { get; set; }
    public string emisiones { get; set; }
    public string productos { get; set; }
    public string desechos { get; set; }
    public string foto { get; set; }

    public virtual area area { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<at_it_el_pa> at_it_el_pa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<identificacion_puesto> identificacion_puesto { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<puesto_trabajo_epp> puesto_trabajo_epp { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador> trabajador { get; set; }
}

public partial class puesto_trabajo_epp
{
    public int id_puesto_trabajo_epp { get; set; }
    public Nullable<int> id_puesto_trabajo { get; set; }
    public Nullable<int> id_epp { get; set; }

    public virtual epp epp { get; set; }
    public virtual puesto_trabajo puesto_trabajo { get; set; }
}

public partial class Region
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Region()
    {
        this.departamento = new HashSet<departamento>();
    }

    public int id_region { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<departamento> departamento { get; set; }
}

public partial class Respuesta
{
    public int id_respuesta { get; set; }
    public string usuario { get; set; }
    public string cuerpo_respuesta { get; set; }
    public Nullable<int> id_pregunta { get; set; }
    public Nullable<int> calificacion { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }

    public virtual Pregunta Pregunta { get; set; }
}

public partial class riesgos_item
{
    public int id_riesgos_item { get; set; }
    public Nullable<int> id_item { get; set; }
    public Nullable<int> id_enfermedad_laboral { get; set; }
    public Nullable<int> id_factor_riesgo { get; set; }

    public virtual claseCiiu claseCiiu { get; set; }
    public virtual enfermedadLaboral enfermedadLaboral { get; set; }
    public virtual factor_riesgo factor_riesgo { get; set; }
}

public partial class rol
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public rol()
    {
        this.usuario = new HashSet<usuario>();
    }

    public int id_rol { get; set; }
    public string nombre { get; set; }
    public Nullable<int> id_empresa { get; set; }

    public virtual empresa empresa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class seccionCiiu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public seccionCiiu()
    {
        this.divisionCiiu = new HashSet<divisionCiiu>();
    }

    public int id_seccion { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<divisionCiiu> divisionCiiu { get; set; }
}

public partial class sistema
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sistema()
    {
        this.trabajador_estatus = new HashSet<trabajador_estatus>();
    }

    public int id_sistemas { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_estatus> trabajador_estatus { get; set; }
}

public partial class soporte
{
    public int id_soporte { get; set; }
    public string url { get; set; }
    public Nullable<int> id_tabla { get; set; }
    public string tabla { get; set; }

    public virtual at_it_el_pa at_it_el_pa { get; set; }
    public virtual documento documento { get; set; }
    public virtual obligacion obligacion { get; set; }
}

public partial class sucursal
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public sucursal()
    {
        this.area = new HashSet<area>();
        this.brigada_emergencia = new HashSet<brigada_emergencia>();
        this.documento = new HashSet<documento>();
        this.lista_actividad = new HashSet<lista_actividad>();
        this.matriz_responsabilidad = new HashSet<matriz_responsabilidad>();
        this.norma_sucursal = new HashSet<norma_sucursal>();
        this.plan = new HashSet<plan>();
        this.tipo_documento = new HashSet<tipo_documento>();
    }

    public int id_sucursal { get; set; }
    public string nombre { get; set; }
    public Nullable<int> id_municpio { get; set; }
    public Nullable<int> id_empresa { get; set; }
    public string direccion { get; set; }
    public Nullable<int> sede_principal { get; set; }
    public string representante { get; set; }
    public string movil { get; set; }
    public string fijo { get; set; }
    public Nullable<int> actividad_ppal { get; set; }
    public Nullable<int> actividad_sec { get; set; }
    public Nullable<int> actividad_otra { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<area> area { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<brigada_emergencia> brigada_emergencia { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<documento> documento { get; set; }
    public virtual empresa empresa { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<lista_actividad> lista_actividad { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<matriz_responsabilidad> matriz_responsabilidad { get; set; }
    public virtual municipio municipio { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<norma_sucursal> norma_sucursal { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<plan> plan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tipo_documento> tipo_documento { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tipo_documento
{
    public int id_tipo_documento { get; set; }
    public Nullable<int> id_sucursal { get; set; }
    public string nombre { get; set; }
    public string dirigida { get; set; }
    public string modalidad { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public string responsable { get; set; }
    public string aprobado { get; set; }
    public string archivado { get; set; }
    public string estatus { get; set; }

    public virtual sucursal sucursal { get; set; }
}

public partial class tipo_epp
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipo_epp()
    {
        this.epp = new HashSet<epp>();
    }

    public int id_tipo_epp { get; set; }
    public string nombre { get; set; }
    public string nombre_senal { get; set; }
    public string url_senal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<epp> epp { get; set; }
}

public partial class tipo_evento
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipo_evento()
    {
        this.evento = new HashSet<evento>();
    }

    public int id_tipo_evento { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<evento> evento { get; set; }
}

public partial class tipo_examen
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipo_examen()
    {
        this.historia_clinica_ocupacional = new HashSet<historia_clinica_ocupacional>();
    }

    public int id_tipo_exa { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<historia_clinica_ocupacional> historia_clinica_ocupacional { get; set; }
}

public partial class tipo_riesgo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipo_riesgo()
    {
        this.factor_riesgo = new HashSet<factor_riesgo>();
    }

    public int id_tipo_riesgo { get; set; }
    public string nombre { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<factor_riesgo> factor_riesgo { get; set; }
}

public partial class trabajador
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public trabajador()
    {
        this.at_it_el_pa = new HashSet<at_it_el_pa>();
        this.desc_socio = new HashSet<desc_socio>();
        this.documento = new HashSet<documento>();
        this.encuesta_politica = new HashSet<encuesta_politica>();
        this.historia_clinica_ocupacional = new HashSet<historia_clinica_ocupacional>();
        this.trabajador_estatus = new HashSet<trabajador_estatus>();
        this.trabajador_gestion = new HashSet<trabajador_gestion>();
        this.usuario = new HashSet<usuario>();
    }

    public int id_trabajador { get; set; }
    public string cedula { get; set; }
    public string primer_nombre { get; set; }
    public string segundo_nombre { get; set; }
    public string primer_apellido { get; set; }
    public string segundo_apellido { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    public string edo_civil { get; set; }
    public string sexo { get; set; }
    public string foto { get; set; }
    public string telefono_casa { get; set; }
    public string telefono_movil { get; set; }
    public Nullable<int> activo { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public string direccion { get; set; }
    public int id_municipio { get; set; }
    public int id_puesto_trabajo { get; set; }
    public string es_discapacitado { get; set; }
    public string desc_discapacidad { get; set; }
    public Nullable<int> id_horario { get; set; }
    public Nullable<int> id_estatus_actual { get; set; }
    public Nullable<int> id_ccf { get; set; }
    public Nullable<System.DateTime> fecha_ingreso { get; set; }
    public string tipo_vinculacion { get; set; }
    public string codigo_independiente { get; set; }
    public string tipo_horario { get; set; }
    public Nullable<int> id_perfil_cargo { get; set; }
    public Nullable<double> salario { get; set; }
    public string mano_dominante { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<at_it_el_pa> at_it_el_pa { get; set; }
    public virtual ccf ccf { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<desc_socio> desc_socio { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<documento> documento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<encuesta_politica> encuesta_politica { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<historia_clinica_ocupacional> historia_clinica_ocupacional { get; set; }
    public virtual municipio municipio { get; set; }
    public virtual perfil_cargo perfil_cargo { get; set; }
    public virtual puesto_trabajo puesto_trabajo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_estatus> trabajador_estatus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<trabajador_gestion> trabajador_gestion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<usuario> usuario { get; set; }
}

public partial class trabajador_estatus
{
    public int id_trabajador_estatus { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public string motivo { get; set; }
    public Nullable<int> id_enfermedad { get; set; }
    public Nullable<int> id_sistema { get; set; }
    public Nullable<int> dias_reposo { get; set; }
    public Nullable<System.DateTime> fecha_constancia { get; set; }
    public string url_constancia { get; set; }
    public string tpo_enfermedad { get; set; }

    public virtual enfermedad enfermedad { get; set; }
    public virtual estatus estatus { get; set; }
    public virtual sistema sistema { get; set; }
    public virtual trabajador trabajador { get; set; }
}

public partial class trabajador_gestion
{
    public int id_trabajador { get; set; }
    public int id_ges_lab { get; set; }
    public string asistencia { get; set; }
    public int id_trabajador_gestion { get; set; }

    public virtual gestion_laboral gestion_laboral { get; set; }
    public virtual trabajador trabajador { get; set; }
}

public partial class usuario
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public usuario()
    {
        this.alarma = new HashSet<alarma>();
        this.evento = new HashSet<evento>();
        this.gestion_laboral = new HashSet<gestion_laboral>();
        this.obligacion = new HashSet<obligacion>();
        this.plan_trabajo = new HashSet<plan_trabajo>();
        this.Pregunta = new HashSet<Pregunta>();
    }

    public int id_usuario { get; set; }
    public string login { get; set; }
    public string clave { get; set; }
    public Nullable<int> id_trabajador { get; set; }
    public Nullable<int> id_rol { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<alarma> alarma { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<evento> evento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<gestion_laboral> gestion_laboral { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<obligacion> obligacion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<plan_trabajo> plan_trabajo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Pregunta> Pregunta { get; set; }
    public virtual rol rol { get; set; }
    public virtual trabajador trabajador { get; set; }
}
