//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class norma_sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public norma_sucursal()
        {
            this.medida_sucursal = new HashSet<medida_sucursal>();
        }
    
        public int id_normas_sucursal { get; set; }
        public Nullable<int> id_sucursal { get; set; }
        public Nullable<int> id_normas { get; set; }
        public Nullable<int> estatus_norma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medida_sucursal> medida_sucursal { get; set; }
        public virtual norma norma { get; set; }
        public virtual sucursal sucursal { get; set; }
    }
}
