//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class politica_sst
    {
        public int id_politica { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> anho { get; set; }
        public string ruta { get; set; }
        public string nombre_archivo { get; set; }
        public string compromiso { get; set; }
        public string objetivos { get; set; }
        public string alcance { get; set; }
    
        public virtual empresa empresa { get; set; }
    }
}
