//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class puesto_trabajo_epp
    {
        public int id_puesto_trabajo_epp { get; set; }
        public Nullable<int> id_puesto_trabajo { get; set; }
        public Nullable<int> id_epp { get; set; }
    
        public virtual epp epp { get; set; }
        public virtual puesto_trabajo puesto_trabajo { get; set; }
    }
}
