//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class puesto_trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public puesto_trabajo()
        {
            this.at_it_el_pa = new HashSet<at_it_el_pa>();
            this.identificacion_puesto = new HashSet<identificacion_puesto>();
            this.puesto_trabajo_epp = new HashSet<puesto_trabajo_epp>();
            this.trabajador = new HashSet<trabajador>();
        }
    
        public int id_puesto_trabajo { get; set; }
        public string nombre { get; set; }
        public int id_area { get; set; }
        public string descripcion { get; set; }
        public string recurso_humano { get; set; }
        public string objeto_trabajo { get; set; }
        public string insumos { get; set; }
        public string maquinas { get; set; }
        public string herramientas { get; set; }
        public string emisiones { get; set; }
        public string productos { get; set; }
        public string desechos { get; set; }
        public string foto { get; set; }
    
        public virtual area area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<at_it_el_pa> at_it_el_pa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<identificacion_puesto> identificacion_puesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<puesto_trabajo_epp> puesto_trabajo_epp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajador> trabajador { get; set; }
    }
}
