//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class riesgos_item
    {
        public int id_riesgos_item { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_enfermedad_laboral { get; set; }
        public Nullable<int> id_factor_riesgo { get; set; }
    
        public virtual claseCiiu claseCiiu { get; set; }
        public virtual enfermedadLaboral enfermedadLaboral { get; set; }
        public virtual factor_riesgo factor_riesgo { get; set; }
    }
}
