//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class soporte
    {
        public int id_soporte { get; set; }
        public string url { get; set; }
        public Nullable<int> id_tabla { get; set; }
        public string tabla { get; set; }
    
        public virtual at_it_el_pa at_it_el_pa { get; set; }
        public virtual documento documento { get; set; }
        public virtual obligacion obligacion { get; set; }
    }
}
