using System.Web;
using System.Web.Services;
using System.Web.Script.Services;
using System.Collections.Generic;
using Capa_Datos;
using System;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Text;

namespace SGSSTC.source.sistema.EvaluacionInicial
{
	public partial class create_InspeccionPuestos : Page
	{
		private Model_UsuarioSistema ObjUsuario;
		private Tuple<bool, bool> BoolEmpSuc;
		private static int IdSucursal = 0;
		private static int IdTrabajador = 0;

		#region Index
		protected void Page_Load(object sender, EventArgs e)
		{
			ObjUsuario = Utilidades.ValidarSesion(HttpContext.Current.User.Identity as FormsIdentity, this);phAlerta.Visible = false;

			BoolEmpSuc = Getter.Get_Empresa_Sucursal(ObjUsuario);

			phEmpresa.Visible = BoolEmpSuc.Item1;
			phSucursal.Visible = BoolEmpSuc.Item2;

			if (!IsPostBack)
			{
				CargarListas();
			}
		}

		private void CargarListas()
		{
			if (BoolEmpSuc.Item1)
			{
				Listas.Empresa(ddlEmpresa);
			}
			else
			{
				Listas.Sucursal(ddlSucursal, ObjUsuario.Id_empresa);
			}

			if (!BoolEmpSuc.Item2)
			{
				Listas.Area_Sucursal(ddlArea, ObjUsuario.Id_sucursal);
			}

		}
		#endregion

		#region Imprimir
		protected void btnGenerarResultados_Click(object sender, EventArgs e)
		{
			int TotalFavorable = 0, TotalDesfavorable = 0;
			RadioButton[] Radios =
				{
				chkSi1,
				chkNo1,
				chkSi2,
				chkNo2,
				chkSi3,
				chkNo3,
				chkSi4,
				chkNo4,
				chkSi5,
				chkNo5,
				chkSi6,
				chkNo6,
				chkSi7,
				chkNo7,
				chkSi8,
				chkNo8,
				chkSi9,
				chkNo9,
				chkSi10,
				chkNo10,
				chkSi11,
				chkNo11,
				chkSi12,
				chkNo12,
				chkSi13,
				chkNo13,
				chkSi14,
				chkNo14,
				chkSi15,
				chkNo15,
				chkSi16,
				chkNo16,
				chkSi17,
				chkNo17,
				chkSi18,
				chkNo18,
				chkSi19,
				chkNo19,
				chkSi20,
				chkNo20,
				chkSi21,
				chkNo21,
				chkSi22,
				chkNo22,
				chkSi23,
				chkNo23,
				chkSi24,
				chkNo24,
				chkSi25,
				chkNo25,
				chkSi26,
				chkNo26,
				chkSi27,
				chkNo27,
				chkSi28,
				chkNo28,
				chkSi29,
				chkNo29,
				chkSi30,
				chkNo30,
				chkSi31,
				chkNo31,
				chkSi32,
				chkNo32,
				chkSi33,
				chkNo33,
				chkSi34,
				chkNo34,
				chkSi35,
				chkNo35,
				chkSi36,
				chkNo36,
				chkSi37,
				chkNo37,
				chkSi38,
				chkNo38,
				chkSi39,
				chkNo39,
				chkSi40,
				chkNo40,
				chkSi41,
				chkNo41,
				chkSi42,
				chkNo42,
				chkSi43,
				chkNo43,
				chkSi44,
				chkNo44,
				chkSi45,
				chkNo45,
				chkSi46,
				chkNo46,
				chkSi47,
				chkNo47,
				chkSi48,
				chkNo48,
				chkSi49,
				chkNo49,
				chkSi50,
				chkNo50,
				chkSi51,
				chkNo51,
				chkSi52,
				chkNo52,
				chkSi53,
				chkNo53,
				chkSi54,
				chkNo54,
				chkSi55,
				chkNo55,
				chkSi56,
				chkNo56,
				chkSi57,
				chkNo57,
				chkSi58,
				chkNo58,
				chkSi59,
				chkNo59,
				chkSi60,
				chkNo60,
				chkSi61,
				chkNo61,
				chkSi62,
				chkNo62,
				chkSi63,
				chkNo63,
				chkSi64,
				chkNo64,
				chkSi65,
				chkNo65,
				chkSi66,
				chkNo66,
				chkSi67,
				chkNo67,
				chkSi68,
				chkNo68,
				chkSi69,
				chkNo69,
				chkSi70,
				chkNo70,
				chkSi71,
				chkNo71,
				chkSi72,
				chkNo72,
				chkSi73,
				chkNo73,
				chkSi74,
				chkNo74,
				chkSi75,
				chkNo75,
				chkSi76,
				chkNo76,
				chkSi77,
				chkNo77,
				chkSi78,
				chkNo78,
				chkSi79,
				chkNo79,
				chkSi80,
				chkNo80,
				chkSi81,
				chkNo81,
				chkSi82,
				chkNo82,
				chkSi83,
				chkNo83,
				chkSi84,
				chkNo84,
				chkSi85,
				chkNo85,
				chkSi86,
				chkNo86,
				chkSi87,
				chkNo87,
				chkSi88,
				chkNo88,
				chkSi89,
				chkNo89,
				chkSi90,
				chkNo90,
				chkSi91,
				chkNo91,
				chkSi93,
				chkNo93,
				chkSi94,
				chkNo94,
				chkSi95,
				chkNo95,
				chkSi96,
				chkNo96,
				chkSi97,
				chkNo97,
				chkSi98,
				chkNo98,
				chkSi99,
				chkNo99,
				chkSi100,
				chkNo100,
				chkSi101,
				chkNo101,
				chkSi102,
				chkNo102,
				chkSi103,
				chkNo103,
				chkSi104,
				chkNo104,
				chkSi105,
				chkNo105,
				chkSi106,
				chkNo106,
				chkSi107,
				chkNo107,
				chkSi108,
				chkNo108,
				chkSi109,
				chkNo109,
				chkSi110,
				chkNo110,
				chkSi111,
				chkNo111,
				chkSi112,
				chkNo112,
				chkSi113,
				chkNo113,
				chkSi114,
				chkNo114,
				chkSi115,
				chkNo115,
				chkSi116,
				chkNo116,
				chkSi117,
				chkNo117,
				chkSi118,
				chkNo118,
				chkSi119,
				chkNo119,
				chkSi120,
				chkNo120,
				chkSi121,
				chkNo121,
				chkSi122,
				chkNo122,
				chkSi123,
				chkNo123,
				chkSi124,
				chkNo124,
				chkSi125,
				chkNo125,
				chkSi126,
				chkNo126,
				chkSi127,
				chkNo127,
				chkSi128,
				chkNo129,
				chkSi129,
				chkNo129,
				chkSi130,
				chkNo130,
				chkSi131,
				chkNo131,
				chkSi132,
				chkNo132,
				chkSi133,
				chkNo133,
				chkSi134,
				chkNo134,
				chkSi135,
				chkNo135,
				chkSi136,
				chkNo136,
				chkSi137,
				chkNo137,
				chkSi138,
				chkNo138,
				chkSi139,
				chkNo139,
				chkSi140,
				chkNo140,
				chkSi141,
				chkNo141,
				chkSi142,
				chkNo142,
				chkSi143,
				chkNo143,
				chkSi144,
				chkNo144,
				chkSi145,
				chkNo145,
				chkSi146,
				chkNo146,
				chkSi147,
				chkNo147,
				chkSi148,
				chkNo148,
				chkSi149,
				chkNo149,
				chkSi150,
				chkNo150,
				chkSi151,
				chkNo151,
				chkSi152,
				chkNo152,
				chkSi153,
				chkNo153,
				chkSi154,
				chkNo154,
				chkSi155,
				chkNo155,
				chkSi156,
				chkNo156
			};

			int[] valores = ControlesDinamicos.GenerarResultados_InspeccionPuestos(Radios);
			TotalFavorable = valores[0];
			TotalDesfavorable = valores[1];

			generarGrafica(TotalFavorable, TotalDesfavorable);
			lblSumaSi.Text = "" + TotalFavorable;
			lblSumaNo.Text = "" + TotalDesfavorable;

			int porcentaje = (TotalDesfavorable * 100) / (TotalFavorable + TotalDesfavorable);

			lblResultado.Text = "El " + porcentaje + " %, indican condiciones de trabajo que pueden estar asociadas a alto riesgo de lesión o enfermedad.";

			phDocumento.Visible = true;
			phDocumento1.Visible = false;
			phGrafica.Visible = true;
		}

		private void generarGrafica(int TotalSi, int TotalNo)
		{
			Double[] yAsistencias = { TotalSi, TotalNo };
			String[] xCadenas = { "SI", "NO" };
			//graficaPie.ChartAreas[0].AxisX.LabelStyle.Interval = 1;
			//graficaPie.Series["seriesPie"].Points.DataBindXY(xCadenas, yAsistencias);
			//graficaPie.SaveImage(Server.MapPath("~/archivos/images_graf/graficaInspPO.jpg"));
			StringBuilder str = new StringBuilder();
			str.Append(@"<script type = *text/javascript* >
					   google.load( *visualization*, *1*, {packages:[*corechart*]});
					   google.setOnLoadCallback(drawChart);
						function drawChart()
						{
							var data = google.visualization.arrayToDataTable([
	
							  ['Task', 'Hours per Day'],
	
							  ['SI', " + TotalSi + "],");
			str.Append(@"['NO'," + TotalNo + "]]); ");

			str.Append(@"var options = {
						  title: 'Puestos Operativos',
						  is3D: true,
						  width: 1000, 
						  height: 350,
						};

						var chart = new google.visualization.PieChart(document.getElementById('piechart'));
						chart.draw(data, options);
						
						$('#ImgChart').attr('src', chart.getImageURI());
						$('#rutaImg').val(chart.getImageURI());

					}
					</script>");

			string Myscript = str.ToString().Replace('*', '"');
			ltReporte.Text = Myscript;
			btnGenerarResultados.Focus();
		}

		protected void GenerarDocumento(object sender, EventArgs e)
		{
			Tuple<int, int> IdEmpSuc = Getter.Get_IdEmpresa_IdSucursal(ObjUsuario, ddlEmpresa, ddlSucursal);
			String[] valores = {
				 string.Empty + IdEmpSuc.Item2,
				 "Área a Inspeccionar: " + ddlArea.SelectedItem.Text,
				 "Fecha: " + DateTime.Today.Date.ToString("yyyy-MM-dd"),
				 "Datos del Trabajador: " + ddlTrabajador.SelectedItem.Text,
				 "Cargo: " + ddlPuesto.SelectedItem.Text,
				 "N°",
				 "ORGANIZACIÓN DE TRABAJO",
				 "SI",
				 "NO",
				 "OBSERVACIONES",
				 txtObsGenerales.Text
			};

			String[] titulos ={
				"¿La jornada laboral semanal excede de 48 Horas?",
				"¿Se realizan horas extras luego de la jornada de trabajo? y esto es un factor estresante para el trabajador (a)?",
				"¿Existe rotación en los turnos de trabajo (día – noche), y esto es un factor estresante para el trabajador (a)?",
				"¿Durante la jornada laboral, los descansos ó pausas son escasos ó nulos?",
				"¿Se impone un ritmo de trabajo difícil de alcanzar para el trabajador ?",
				"¿El trabajador está expuesto a temperaturas extremas?",
				"¿Existen variaciones extremas de temperatura durante la jornada?",
				"¿Es bajo el nivel de iluminación en el área de trabajo?",
				"¿Existen deslumbramientos en el área de trabajo?",
				"¿Existen sombras por falta de iluminación en el área de trabajo?",
				"¿Es baja la frecuencia de limpieza en la lámparas y ventanas?",
				"¿Las lámparas fundidas son sustituidas con baja frecuencia?",
				"¿Hay ruido excesivo,constante y molesto?",
				"¿Hay vibración de cuerpo completo o de las extremidades superiores?",
				"¿Se emplean herramientas que produzcan vibraciones (martillo neumático, buril, pulidora, etc.), sin sistemas de amortiguación?",
				"¿Existen máquinas que producen vibraciones?",
				"¿La circulación de aire en el área de trabajo es insuficiente?",
				"¿El trabajador mantiene una postura prolongada durante el 75% o más de la jornada laboral sin alternarla (de pie o sentado)?",
				"¿Existen rotaciones e inclinaciones repetidas de cuello?",
				"¿Hay flexiones repetidas de la espalda o tronco mayores de 30°?",
				"¿Hay rotaciones de la espalda o tronco?",
				"¿El trabajador realiza de manera prolongada actividades arrodillado y/o en cuclillas?",
				"¿Existen posturas de los hombros en flexión mayor de 45°?",
				"¿Existen posturas donde el hombro se encuentra en abducción mayor de 45°?",
				"¿Existen posturas donde los codos se encuentren en flexión mayor de 90°?",
				"¿Existen posturas donde se exija levantar y sostener el codo por encima del nivel de la mitad del pecho?",
				"¿Existen posturas del tronco en contra de la gravedad?",
				"¿Existen posturas de los miembros superiores en contra de la gravedad?",
				"¿Hay desviaciones en manos con relación al eje neutro de la muñeca en la manipulación o agarre de herramientas u objetos?",
				"¿Hay repetitividad de movimientos idénticos o similares efectuados cada pocos segundos en los miembros superiores?",
				"¿Hay movimientos del tronco con combinación de fuerza?",
				"¿Existe movimientos repetidos para alcanzar algo que se encuentre detrás de la persona?",
				"¿Hay movimientos de los miembros superiores con combinación de fuerza?",
				"¿Existen posturas de elevación sostenida o repetida de los brazos?",
				"¿La tarea involucra posturas no-neutrales y repetidas de la mano ?",
				"¿La tarea involucra movimientos rápidos, fuertes o repentinos de los miembros superiores en posiciones forzadas?",
				"¿La tarea requiere esfuerzos enérgicos de la mano con el brazo extendido?",
				"¿La tarea exige mover la cabeza repetidamente de un lado a otro?",
				"¿La tarea exige flexión del tronco hacia adelante mas de 20º?",
				"¿La tarea implica Inclinación lateral del tronco, repetidas veces?",
				"¿Se debe Rotar el tronco en más de 20º?",
				"¿La tarea involucra movimientos rápidos, fuertes o repentinos de la espalda en posiciones forzadas?",
				"¿ El trabajo requiere levantar cargas compactas? (para hombres 25 kilos y mujeres 12.5 kilos)",
				"¿ Para aquellos trabajadores dedicados constantemente al levantamiento y transporte de carga, los intervalos de pausa, o períodos libres de esfuerzo físico extraordinario son escasos o núlos y esto no les permite una recuperación de la fátiga?",
				"¿El trabajador levanta peso por debajo de las rodillas ó arriba de los hombros repetidas veces al día?",
				"¿El trabajador empuja o hala 10 o más kilos durante 2 o más horas consecutivas?",
				"¿El trabajador manipula objetos o herramientas de un peso igual o mayor a 2 kilogramos por mano?",
				"¿Hay manipulación de objetos o herramientas por encima de los hombros ?",
				"¿Hay manipulación de objetos o herramientas por debajo de la cintura ?",
				"¿Hay inclinación del tronco al manipular objetos o cargas?",
				"¿Hay giros o torsiones de tronco al manipular objetos o cargas?",
				"¿Hay desplazamientos del cuerpo mientras se manipulan los objetos o las cargas, y la manipulación se realiza de manera indecuada (la carga alejada del cuerpo y la misma no posee un agarre adecuado ?",
				"¿El trabajo exige simultáneamente varias tareas?",
				"¿La tarea tiene un grado alto de concentración requiere de una elevada concentración sostenida y contínua, lo cual no es posible debido a factores externos ?",
				"¿Se requiere velocidad en el proceso para la realización de la tarea?",
				"¿El trabajo implica el control de varias señales ?",
				"¿El trabajo es minucioso y requiere de precisión?",
				"¿Existe un alto riesgo de accidentalidad en la manipulación de herramientas?",
				"¿La realización de la tarea prohíbe hablar con otros compañeros mientras se trabaja, y no se permiten pausas de descanso?",
				"¿La altura del plano de trabajo genera inclinaciones de tronco?",
				"¿Los elementos de trabajo se encuentran fuera del alcance del trabajador?",
				"¿La visibilidad de todos los elementos de trabajo implica adoptar posturas inadecuadas o no confortables para el trabajador?",
				"¿El espacio de trabajo limita el libre movimiento?",
				"¿La manipulación de cargas se realiza sin ayudas mecánicas?",
				"¿Se carece de elementos que permitan alternar posturas y/o que brinden confort (silla, reposa pies o banca para alternar posturas)?",
				"¿La superficie de trabajo exige posturas de los miembros superiores en contra de la gravedad?",
				"¿La silla utilizada es estática ?",
				"¿El asiento es inadecuado a las dimensiones del usuario (profundidad y anchura)?",
				"¿La silla es incómoda para el usuario?",
				"¿La herramienta de trabajo es inadecuada a las necesidades del trabajador en cuanto a la funcionalidad para ejecutar la tarea?",
				"¿Las dimensiones del mango y la naturaleza del agarre son inadecuados a las dimensiones de la mano del trabajador?",
				"¿Se usan herramientas o equipos que tengan altos niveles de vibración (sierras eléctricas, martillos neumáticos, herramientas de percusión, martillos de remachado)?",
				"¿Existen focos de calor (hornos, calderas, etc.) sin aislar convenientemente?",
				"¿Existen condiciones inapropiadas de ventilación en el local?",
				"¿En la operación se generan vapores o humedad?",
				"¿La temperatura del local de trabajo es inadecuada?",
				"¿La ropa de trabajo utilizada es inapropiada al tipo de trabajo y a la temperatura ambiental?",
				"¿El mantenimiento que se realiza a los sistemas de ventilación es ineficaz?",
				"¿El trabajador(a) está expuesto a radiaciones ionizantes y se dota de Equipo de Protección adecuada?",
				"¿Existe señalización del riesgo a exposición de radiaciones ionizantes ?",
				"¿Se realizan evaluaciones médicas periódicas deacuerdo al riesgo al que está expuesto el trabajador?(abstenerse de realizar la selección si no existe el riesgo de radiación)",
				"¿Se utilizan productos químicos en su área de trabajo, y conoce que productos son los que emplea?",
				"¿Los productos químicos están etiquetados adecuadamente?",
				"¿Existen normas establecidas para la utilización de productos químicos peligrosos?",
				"¿Se realizan mediciones periódicas de la concentración del contaminante?",
				"¿Se realizan revisiones médicas periódicas a los trabajadores?",
				"¿ Si se emplean productos tóxicos, ¿ El personal Mantiene condiciones mínimas de higiene? (lavarse las manos antes de comer, no ingresar alimentos al área operativa, cambiarse de ropa al salir del trabajo, etc.)",
				"¿ Antes de incorporar al proceso productivo una sustancia química, ¿Se informan a los trabajadores sobre la hoja de datos de seguridad del producto? ( donde el proveedor detalla los datos del producto, niveles de toxicidad y acciones a seguir en casos de emergencia)",
				"Si se trabaja con manipulación de productos origen animal, laboratorios biológicos y clínicos, hospitales, sanitarios, etc.: ¿Están los aseos, los comedores etc., aislados de la zona de trabajo?",
				"¿Se mantienen los lugares de trabajo, vestuarios, baños, comedores, etc., en perfectas condiciones de limpieza y desinfección?",
				"¿Se mantienen condiciones mínimas de higiene personal? (lavarse las manos antes de comer, no ingresar alimentos al área operativa, cambiarse de ropa al salir del trabajo, etc.)",
				//"Los esfuerzos realizados en el desarrollo de la labor están adecuados al trabajador (a) respecto a:",
				"¿Su capacidad física?",
				"¿A la temperatura ambiental?",
				"¿A su edad?",
				"¿A su entrenamiento?",
				"Si el trabajador realiza un trabajo muy pesado ¿ Se le hacen revisiones para controlar la frecuencia cardiaca?",
				"¿Se realizan una evaluación de consumo metabólico con respecto a la actividad que realiza el trabajador(a)?",
				"¿Se informa sobre las posibles Enfermedades Ocupacionales detectadas en la Empresa?",
				"¿Se informa de los accidentes de trabajo ocurridos en el último año?",
				"¿ Se informa a los trabjadores sobre las causas?",
				"¿La Empresa informa por escrito o por medio de charlas a los trabajadores de los riesgos presentes?",
				"¿Se miden y controlan los niveles de contaminación existentes en los puestos de trabajo?",
				"Ante las Enfermedades Ocupacionales ¿Se efectúa un estudio de las causas que las originan?",
				"Ante los Accidentes Laborales ¿Se realiza la investigación del evento?",
				"¿Se le informa al personal sobre las posibles Enfermedades Ocupacionales detectadas en la Empresa?",
				"¿Se informa de los accidentes de trabajo ocurridos en el último año?",
				"¿Se miden y controlan los niveles de contaminación existentes en los puestos de trabajo?",
				"Ante las Enfermedades Ocupacionales ¿Se efectúa un estudio de las causas que las originan?",
				"Ante los Accidentes Laborales ¿Se realiza la investigación del evento?",
				"¿Se dota al personal de Equipos de Protección Personal?",
				"¿Son adecuados al riesgo que deben proteger?",
				"¿Son de uso personal?",
				"¿Se revisan periódicamente?",
				"¿Se exige su uso obligatorio?",
				"¿Se inspecciona el cumplimiento del uso del equipo de protección?",
				"¿Se realizan capacitaciones respecto a temas de Seguridad y Salud en el Trabajo?",
				"¿Se realizan simulacros de evacuación?",
				"¿La empresa cumple con las señalizaciones de rutas de evacuación?",
				"¿Existe definido un plan de evacuación?",
				"¿Se exige su uso obligatorio?¿Están definidos cuales son los puntos de reunión después de una evacuación?",
				"¿Se capacita al personal sobre el uso correcto de los equipos de extinción?",
				"¿El personal conoce donde están ubicados los extintores?",
				"¿Es de conocimiento del personal donde están ubicadas las tomas de manguera para incendio?",
				"¿Se ha conformado la brigada de emergencia?",
				"¿El trabajador tiene algún tipo de control sobre el proceso de trabajo?",
				"¿Los Programas a utilizar en sus tareas diarias son fáciles de utilizar?",
				"¿Se entrena al trabajador (a) para utilizar un nuevo software?",
				"¿Existe comunicación asertiva entre los trabajadores y el supervisor?",
				"¿El trabajo está organizado de manera que no se exija simultáneamente varias tareas ?",
				"¿ Si la tarea requiere de una elevada concentración, se evitan los agentes distractores en el lugar de trabajo?",
				"¿ En la organización se evita laborar horas extras luego de la jornada de trabajo?",
				"¿Existen equipos Extintores?",
				"¿Existe botiquín de Primeros Auxilios suficientemente dotado y revisado periódicamente?",
				"¿ Está señalizada la vía de Evacuación?",
				"¿ Existe alumbrado de Emergencia?",
				"¿Son óptimas las condiciones del Techo?",
				"¿ El piso de la instalación se en encuentra en buenas condiciones?",
				"¿ Las paredes del local son óptimas?",
				"¿ Las puertas se encuentran en buen estado?",
				"¿ Las escaleras tienen pasa manos?",
				"¿ las áreas están señalizadas?",
				"¿ El sitio de trabajo tiene la ventilación adecuada?",
				"¿Es óptimo el Estado de los Cables (Entubado)?",
				"¿Es óptimo el Estado del toma corriente?",
				"¿Es óptimo el Estado del Tablero eléctrico?",
				"¿Es óptimo el estado de los Bombillos/Tubos Fluorescentes?",
				"¿Las instalaciones usadas para la alimentación son apropiadas?",
				"¿Se encuentran en estado óptimo de limpieza?",
				"¿Su ubicación es alejada de depósitos y de áreas que posean riesgo de contaminación?",
				"¿Los espacios sanitarios son adecuados?",
				"¿Existe disponibilidad de Jabón en los espacios sanitarios?",
				"¿Existe disponibilidad de papel higiénico en los espacios sanitarios?",
				"¿Existen filtros de agua potable en la empresa?",
				"¿Posee la empresa áreas para el descanso y la recreación?",
				"¿En las instalaciones sanitarias se mantiene el orden y limpieza?"
			};

			String[] encabezados = {
				"ASPECTO A EVALUAR DEL AMBIENTE",
				"ASPECTO A EVALUAR CARGA FISICA DEL TRABAJO",
				"MANIPULACIÓN DE CARGA",
				"CARGA MENTAL",
				"CONDICIONES DEL PUESTO DE TRABAJO",
				"CONDICIONES TERMOHIGROMETRICAS",
				"RADIACIONES",
				"CONTAMINANTES QUÍMICOS",
				"CONTAMINANTES BIOLÓGICOS",
				"FATIGA FÍSICA, Los esfuerzos realizados en el desarrollo de la labor están adecuados al trabajador (a) respecto a:",
				"DAÑOS A LA SALUD",
				"EQUIPOS DE PROTECCIÓN PERSONAL",
				"CAPACITACIÓN O INFORMACIÓN",
				"ASPECTOS PSICOSOCIALES",
				"EQUIPOS DE EMERGENCIA",
				"ASPECTOS LOCATIVOS",
				"INSTALACIONES ELÉCTRICAS",
				"OTRAS CONDICIONES"
			};

			String[] valoresno = {
				PrintFile.GetRadioValue(chkNo1),
				PrintFile.GetRadioValue(chkNo2),
				PrintFile.GetRadioValue(chkNo3),
				PrintFile.GetRadioValue(chkNo4),
				PrintFile.GetRadioValue(chkNo5),
				PrintFile.GetRadioValue(chkNo6),
				PrintFile.GetRadioValue(chkNo7),
				PrintFile.GetRadioValue(chkNo8),
				PrintFile.GetRadioValue(chkNo9),
				PrintFile.GetRadioValue(chkNo10),
				PrintFile.GetRadioValue(chkNo11),
				PrintFile.GetRadioValue(chkNo12),
				PrintFile.GetRadioValue(chkNo13),
				PrintFile.GetRadioValue(chkNo14),
				PrintFile.GetRadioValue(chkNo15),
				PrintFile.GetRadioValue(chkNo16),
				PrintFile.GetRadioValue(chkNo17),
				PrintFile.GetRadioValue(chkNo18),
				PrintFile.GetRadioValue(chkNo19),
				PrintFile.GetRadioValue(chkNo20),
				PrintFile.GetRadioValue(chkNo21),
				PrintFile.GetRadioValue(chkNo22),
				PrintFile.GetRadioValue(chkNo23),
				PrintFile.GetRadioValue(chkNo24),
				PrintFile.GetRadioValue(chkNo25),
				PrintFile.GetRadioValue(chkNo26),
				PrintFile.GetRadioValue(chkNo27),
				PrintFile.GetRadioValue(chkNo28),
				PrintFile.GetRadioValue(chkNo29),
				PrintFile.GetRadioValue(chkNo30),
				PrintFile.GetRadioValue(chkNo31),
				PrintFile.GetRadioValue(chkNo32),
				PrintFile.GetRadioValue(chkNo33),
				PrintFile.GetRadioValue(chkNo34),
				PrintFile.GetRadioValue(chkNo35),
				PrintFile.GetRadioValue(chkNo36),
				PrintFile.GetRadioValue(chkNo37),
				PrintFile.GetRadioValue(chkNo38),
				PrintFile.GetRadioValue(chkNo39),
				PrintFile.GetRadioValue(chkNo40),
				PrintFile.GetRadioValue(chkNo41),
				PrintFile.GetRadioValue(chkNo42),
				PrintFile.GetRadioValue(chkNo43),
				PrintFile.GetRadioValue(chkNo44),
				PrintFile.GetRadioValue(chkNo45),
				PrintFile.GetRadioValue(chkNo46),
				PrintFile.GetRadioValue(chkNo47),
				PrintFile.GetRadioValue(chkNo48),
				PrintFile.GetRadioValue(chkNo49),
				PrintFile.GetRadioValue(chkNo50),
				PrintFile.GetRadioValue(chkNo51),
				PrintFile.GetRadioValue(chkNo52),
				PrintFile.GetRadioValue(chkNo53),
				PrintFile.GetRadioValue(chkNo54),
				PrintFile.GetRadioValue(chkNo55),
				PrintFile.GetRadioValue(chkNo56),
				PrintFile.GetRadioValue(chkNo57),
				PrintFile.GetRadioValue(chkNo58),
				PrintFile.GetRadioValue(chkNo59),
				PrintFile.GetRadioValue(chkNo60),
				PrintFile.GetRadioValue(chkNo61),
				PrintFile.GetRadioValue(chkNo62),
				PrintFile.GetRadioValue(chkNo63),
				PrintFile.GetRadioValue(chkNo64),
				PrintFile.GetRadioValue(chkNo65),
				PrintFile.GetRadioValue(chkNo66),
				PrintFile.GetRadioValue(chkNo67),
				PrintFile.GetRadioValue(chkNo68),
				PrintFile.GetRadioValue(chkNo69),
				PrintFile.GetRadioValue(chkNo70),
				PrintFile.GetRadioValue(chkNo71),
				PrintFile.GetRadioValue(chkNo72),
				PrintFile.GetRadioValue(chkNo73),
				PrintFile.GetRadioValue(chkNo74),
				PrintFile.GetRadioValue(chkNo75),
				PrintFile.GetRadioValue(chkNo76),
				PrintFile.GetRadioValue(chkNo77),
				PrintFile.GetRadioValue(chkNo78),
				PrintFile.GetRadioValue(chkNo79),
				PrintFile.GetRadioValue(chkNo80),
				PrintFile.GetRadioValue(chkNo81),
				PrintFile.GetRadioValue(chkNo82),
				PrintFile.GetRadioValue(chkNo83),
				PrintFile.GetRadioValue(chkNo84),
				PrintFile.GetRadioValue(chkNo85),
				PrintFile.GetRadioValue(chkNo86),
				PrintFile.GetRadioValue(chkNo87),
				PrintFile.GetRadioValue(chkNo88),
				PrintFile.GetRadioValue(chkNo89),
				PrintFile.GetRadioValue(chkNo90),
				PrintFile.GetRadioValue(chkNo91),
				PrintFile.GetRadioValue(chkNo93),
				PrintFile.GetRadioValue(chkNo94),
				PrintFile.GetRadioValue(chkNo95),
				PrintFile.GetRadioValue(chkNo96),
				PrintFile.GetRadioValue(chkNo97),
				PrintFile.GetRadioValue(chkNo98),
				PrintFile.GetRadioValue(chkNo99),
				PrintFile.GetRadioValue(chkNo100),
				PrintFile.GetRadioValue(chkNo101),
				PrintFile.GetRadioValue(chkNo102),
				PrintFile.GetRadioValue(chkNo103),
				PrintFile.GetRadioValue(chkNo104),
				PrintFile.GetRadioValue(chkNo105),
				PrintFile.GetRadioValue(chkNo106),
				PrintFile.GetRadioValue(chkNo107),
				PrintFile.GetRadioValue(chkNo108),
				PrintFile.GetRadioValue(chkNo109),
				PrintFile.GetRadioValue(chkNo110),
				PrintFile.GetRadioValue(chkNo111),
				PrintFile.GetRadioValue(chkNo112),
				PrintFile.GetRadioValue(chkNo113),
				PrintFile.GetRadioValue(chkNo114),
				PrintFile.GetRadioValue(chkNo115),
				PrintFile.GetRadioValue(chkNo116),
				PrintFile.GetRadioValue(chkNo117),
				PrintFile.GetRadioValue(chkNo118),
				PrintFile.GetRadioValue(chkNo119),
				PrintFile.GetRadioValue(chkNo120),
				PrintFile.GetRadioValue(chkNo121),
				PrintFile.GetRadioValue(chkNo122),
				PrintFile.GetRadioValue(chkNo123),
				PrintFile.GetRadioValue(chkNo124),
				PrintFile.GetRadioValue(chkNo125),
				PrintFile.GetRadioValue(chkNo126),
				PrintFile.GetRadioValue(chkNo127),
				PrintFile.GetRadioValue(chkNo128),
				PrintFile.GetRadioValue(chkNo129),
				PrintFile.GetRadioValue(chkNo130),
				PrintFile.GetRadioValue(chkNo131),
				PrintFile.GetRadioValue(chkNo132),
				PrintFile.GetRadioValue(chkNo133),
				PrintFile.GetRadioValue(chkNo134),
				PrintFile.GetRadioValue(chkNo135),
				PrintFile.GetRadioValue(chkNo136),
				PrintFile.GetRadioValue(chkNo137),
				PrintFile.GetRadioValue(chkNo138),
				PrintFile.GetRadioValue(chkNo139),
				PrintFile.GetRadioValue(chkNo140),
				PrintFile.GetRadioValue(chkNo141),
				PrintFile.GetRadioValue(chkNo142),
				PrintFile.GetRadioValue(chkNo143),
				PrintFile.GetRadioValue(chkNo144),
				PrintFile.GetRadioValue(chkNo145),
				PrintFile.GetRadioValue(chkNo146),
				PrintFile.GetRadioValue(chkNo147),
				PrintFile.GetRadioValue(chkNo148),
				PrintFile.GetRadioValue(chkNo149),
				PrintFile.GetRadioValue(chkNo150),
				PrintFile.GetRadioValue(chkNo151),
				PrintFile.GetRadioValue(chkNo152),
				PrintFile.GetRadioValue(chkNo153),
				PrintFile.GetRadioValue(chkNo154),
				PrintFile.GetRadioValue(chkNo155),
				PrintFile.GetRadioValue(chkNo156)
			};

			String[] valoressi = {
				PrintFile.GetRadioValue(chkSi1),
				PrintFile.GetRadioValue(chkSi2),
				PrintFile.GetRadioValue(chkSi3),
				PrintFile.GetRadioValue(chkSi4),
				PrintFile.GetRadioValue(chkSi5),
				PrintFile.GetRadioValue(chkSi6),
				PrintFile.GetRadioValue(chkSi7),
				PrintFile.GetRadioValue(chkSi8),
				PrintFile.GetRadioValue(chkSi9),
				PrintFile.GetRadioValue(chkSi10),
				PrintFile.GetRadioValue(chkSi11),
				PrintFile.GetRadioValue(chkSi12),
				PrintFile.GetRadioValue(chkSi13),
				PrintFile.GetRadioValue(chkSi14),
				PrintFile.GetRadioValue(chkSi15),
				PrintFile.GetRadioValue(chkSi16),
				PrintFile.GetRadioValue(chkSi17),
				PrintFile.GetRadioValue(chkSi18),
				PrintFile.GetRadioValue(chkSi19),
				PrintFile.GetRadioValue(chkSi20),
				PrintFile.GetRadioValue(chkSi21),
				PrintFile.GetRadioValue(chkSi22),
				PrintFile.GetRadioValue(chkSi23),
				PrintFile.GetRadioValue(chkSi24),
				PrintFile.GetRadioValue(chkSi25),
				PrintFile.GetRadioValue(chkSi26),
				PrintFile.GetRadioValue(chkSi27),
				PrintFile.GetRadioValue(chkSi28),
				PrintFile.GetRadioValue(chkSi29),
				PrintFile.GetRadioValue(chkSi30),
				PrintFile.GetRadioValue(chkSi31),
				PrintFile.GetRadioValue(chkSi32),
				PrintFile.GetRadioValue(chkSi33),
				PrintFile.GetRadioValue(chkSi34),
				PrintFile.GetRadioValue(chkSi35),
				PrintFile.GetRadioValue(chkSi36),
				PrintFile.GetRadioValue(chkSi37),
				PrintFile.GetRadioValue(chkSi38),
				PrintFile.GetRadioValue(chkSi39),
				PrintFile.GetRadioValue(chkSi40),
				PrintFile.GetRadioValue(chkSi41),
				PrintFile.GetRadioValue(chkSi42),
				PrintFile.GetRadioValue(chkSi43),
				PrintFile.GetRadioValue(chkSi44),
				PrintFile.GetRadioValue(chkSi45),
				PrintFile.GetRadioValue(chkSi46),
				PrintFile.GetRadioValue(chkSi47),
				PrintFile.GetRadioValue(chkSi48),
				PrintFile.GetRadioValue(chkSi49),
				PrintFile.GetRadioValue(chkSi50),
				PrintFile.GetRadioValue(chkSi51),
				PrintFile.GetRadioValue(chkSi52),
				PrintFile.GetRadioValue(chkSi53),
				PrintFile.GetRadioValue(chkSi54),
				PrintFile.GetRadioValue(chkSi55),
				PrintFile.GetRadioValue(chkSi56),
				PrintFile.GetRadioValue(chkSi57),
				PrintFile.GetRadioValue(chkSi58),
				PrintFile.GetRadioValue(chkSi59),
				PrintFile.GetRadioValue(chkSi60),
				PrintFile.GetRadioValue(chkSi61),
				PrintFile.GetRadioValue(chkSi62),
				PrintFile.GetRadioValue(chkSi63),
				PrintFile.GetRadioValue(chkSi64),
				PrintFile.GetRadioValue(chkSi65),
				PrintFile.GetRadioValue(chkSi66),
				PrintFile.GetRadioValue(chkSi67),
				PrintFile.GetRadioValue(chkSi68),
				PrintFile.GetRadioValue(chkSi69),
				PrintFile.GetRadioValue(chkSi70),
				PrintFile.GetRadioValue(chkSi71),
				PrintFile.GetRadioValue(chkSi72),
				PrintFile.GetRadioValue(chkSi73),
				PrintFile.GetRadioValue(chkSi74),
				PrintFile.GetRadioValue(chkSi75),
				PrintFile.GetRadioValue(chkSi76),
				PrintFile.GetRadioValue(chkSi77),
				PrintFile.GetRadioValue(chkSi78),
				PrintFile.GetRadioValue(chkSi79),
				PrintFile.GetRadioValue(chkSi80),
				PrintFile.GetRadioValue(chkSi81),
				PrintFile.GetRadioValue(chkSi82),
				PrintFile.GetRadioValue(chkSi83),
				PrintFile.GetRadioValue(chkSi84),
				PrintFile.GetRadioValue(chkSi85),
				PrintFile.GetRadioValue(chkSi86),
				PrintFile.GetRadioValue(chkSi87),
				PrintFile.GetRadioValue(chkSi88),
				PrintFile.GetRadioValue(chkSi89),
				PrintFile.GetRadioValue(chkSi90),
				PrintFile.GetRadioValue(chkSi91),
				PrintFile.GetRadioValue(chkSi93),
				PrintFile.GetRadioValue(chkSi94),
				PrintFile.GetRadioValue(chkSi95),
				PrintFile.GetRadioValue(chkSi96),
				PrintFile.GetRadioValue(chkSi97),
				PrintFile.GetRadioValue(chkSi98),
				PrintFile.GetRadioValue(chkSi99),
				PrintFile.GetRadioValue(chkSi100),
				PrintFile.GetRadioValue(chkSi101),
				PrintFile.GetRadioValue(chkSi102),
				PrintFile.GetRadioValue(chkSi103),
				PrintFile.GetRadioValue(chkSi104),
				PrintFile.GetRadioValue(chkSi105),
				PrintFile.GetRadioValue(chkSi106),
				PrintFile.GetRadioValue(chkSi107),
				PrintFile.GetRadioValue(chkSi108),
				PrintFile.GetRadioValue(chkSi109),
				PrintFile.GetRadioValue(chkSi110),
				PrintFile.GetRadioValue(chkSi111),
				PrintFile.GetRadioValue(chkSi112),
				PrintFile.GetRadioValue(chkSi113),
				PrintFile.GetRadioValue(chkSi114),
				PrintFile.GetRadioValue(chkSi115),
				PrintFile.GetRadioValue(chkSi116),
				PrintFile.GetRadioValue(chkSi117),
				PrintFile.GetRadioValue(chkSi118),
				PrintFile.GetRadioValue(chkSi119),
				PrintFile.GetRadioValue(chkSi120),
				PrintFile.GetRadioValue(chkSi121),
				PrintFile.GetRadioValue(chkSi122),
				PrintFile.GetRadioValue(chkSi123),
				PrintFile.GetRadioValue(chkSi124),
				PrintFile.GetRadioValue(chkSi125),
				PrintFile.GetRadioValue(chkSi126),
				PrintFile.GetRadioValue(chkSi127),
				PrintFile.GetRadioValue(chkSi128),
				PrintFile.GetRadioValue(chkSi129),
				PrintFile.GetRadioValue(chkSi130),
				PrintFile.GetRadioValue(chkSi131),
				PrintFile.GetRadioValue(chkSi132),
				PrintFile.GetRadioValue(chkSi133),
				PrintFile.GetRadioValue(chkSi134),
				PrintFile.GetRadioValue(chkSi135),
				PrintFile.GetRadioValue(chkSi136),
				PrintFile.GetRadioValue(chkSi137),
				PrintFile.GetRadioValue(chkSi138),
				PrintFile.GetRadioValue(chkSi139),
				PrintFile.GetRadioValue(chkSi140),
				PrintFile.GetRadioValue(chkSi141),
				PrintFile.GetRadioValue(chkSi142),
				PrintFile.GetRadioValue(chkSi143),
				PrintFile.GetRadioValue(chkSi144),
				PrintFile.GetRadioValue(chkSi145),
				PrintFile.GetRadioValue(chkSi146),
				PrintFile.GetRadioValue(chkSi147),
				PrintFile.GetRadioValue(chkSi148),
				PrintFile.GetRadioValue(chkSi149),
				PrintFile.GetRadioValue(chkSi150),
				PrintFile.GetRadioValue(chkSi151),
				PrintFile.GetRadioValue(chkSi152),
				PrintFile.GetRadioValue(chkSi153),
				PrintFile.GetRadioValue(chkSi154),
				PrintFile.GetRadioValue(chkSi155),
				PrintFile.GetRadioValue(chkSi156)
			};

			String[] textos = {
				txt1.Text,
				txt2.Text,
				txt3.Text,
				txt4.Text,
				txt5.Text,
				txt6.Text,
				txt7.Text,
				txt8.Text,
				txt9.Text,
				txt10.Text,
				txt11.Text,
				txt12.Text,
				txt13.Text,
				txt14.Text,
				txt15.Text,
				txt16.Text,
				txt17.Text,
				txt18.Text,
				txt19.Text,
				txt20.Text,
				txt21.Text,
				txt22.Text,
				txt23.Text,
				txt24.Text,
				txt25.Text,
				txt26.Text,
				txt27.Text,
				txt28.Text,
				txt29.Text,
				txt30.Text,
				txt31.Text,
				txt32.Text,
				txt33.Text,
				txt34.Text,
				txt35.Text,
				txt36.Text,
				txt37.Text,
				txt38.Text,
				txt39.Text,
				txt40.Text,
				txt41.Text,
				txt42.Text,
				txt43.Text,
				txt44.Text,
				txt45.Text,
				txt46.Text,
				txt47.Text,
				txt48.Text,
				txt49.Text,
				txt50.Text,
				txt51.Text,
				txt52.Text,
				txt53.Text,
				txt54.Text,
				txt55.Text,
				txt56.Text,
				txt57.Text,
				txt58.Text,
				txt59.Text,
				txt60.Text,
				txt61.Text,
				txt62.Text,
				txt63.Text,
				txt64.Text,
				txt65.Text,
				txt66.Text,
				txt67.Text,
				txt68.Text,
				txt69.Text,
				txt70.Text,
				txt71.Text,
				txt72.Text,
				txt73.Text,
				txt74.Text,
				txt75.Text,
				txt76.Text,
				txt77.Text,
				txt78.Text,
				txt79.Text,
				txt80.Text,
				txt81.Text,
				txt82.Text,
				txt83.Text,
				txt84.Text,
				txt85.Text,
				txt86.Text,
				txt87.Text,
				txt88.Text,
				txt89.Text,
				txt90.Text,
				txt91.Text,
				txt93.Text,
				txt94.Text,
				txt95.Text,
				txt96.Text,
				txt97.Text,
				txt98.Text,
				txt99.Text,
				txt100.Text,
				txt101.Text,
				txt102.Text,
				txt103.Text,
				txt104.Text,
				txt105.Text,
				txt106.Text,
				txt107.Text,
				txt108.Text,
				txt109.Text,
				txt110.Text,
				txt111.Text,
				txt112.Text,
				txt113.Text,
				txt114.Text,
				txt115.Text,
				txt116.Text,
				txt117.Text,
				txt118.Text,
				txt119.Text,
				txt120.Text,
				txt121.Text,
				txt122.Text,
				txt123.Text,
				txt124.Text,
				txt125.Text,
				txt126.Text,
				txt127.Text,
				txt128.Text,
				txt129.Text,
				txt130.Text,
				txt131.Text,
				txt132.Text,
				txt133.Text,
				txt134.Text,
				txt135.Text,
				txt136.Text,
				txt137.Text,
				txt138.Text,
				txt139.Text,
				txt140.Text,
				txt141.Text,
				txt142.Text,
				txt143.Text,
				txt144.Text,
				txt145.Text,
				txt146.Text,
				txt147.Text,
				txt148.Text,
				txt149.Text,
				txt150.Text,
				txt151.Text,
				txt152.Text,
				txt153.Text,
				txt154.Text,
				txt155.Text,
				txt156.Text
			 };

			PrintFile.PrintInspeccionPuestos(valores, titulos, valoressi, valoresno, textos, encabezados, this);

		}
		#endregion

		#region filtro
		protected void ddlEmpresa_SelectedIndexChanged(object sender, EventArgs e)
		{
			if (ddlEmpresa.SelectedValue != string.Empty)
			{
				ViewState["empresa"] = ddlEmpresa.SelectedValue;
				Listas.Sucursal(ddlSucursal, Convert.ToInt32(ddlEmpresa.SelectedValue));
				ViewState["sucursal"] = "0";
			}
			else
			{
				ViewState["empresa"] = "0";
			}
		}

		protected void ddlSucursal_SelectedIndexChanged(object sender, EventArgs e)
		{
			if (ddlSucursal.SelectedValue != string.Empty)
			{
				ViewState["sucursal"] = ddlSucursal.SelectedValue;
				Listas.Area_Sucursal(ddlArea, Convert.ToInt32(ddlSucursal.SelectedValue), "", "Operativa");
			}
			else
			{
				ViewState["sucursal"] = "0";
			}
		}

		protected void ddlArea_SelectedIndexChanged(object sender, EventArgs e)
		{
			if (ddlArea.SelectedValue != string.Empty)
			{
				ViewState["area"] = ddlArea.SelectedValue;
				Listas.PuestoTrabajo(ddlPuesto, "idArea", Convert.ToInt32(ddlArea.SelectedValue));
			}
			else
			{
				ViewState["area"] = "0";
			}
		}

		protected void ddlPuesto_SelectedIndexChanged(object sender, EventArgs e)
		{
			if (ddlPuesto.SelectedValue != string.Empty)
			{
				ViewState["puesto"] = ddlPuesto.SelectedValue;
				if (!BoolEmpSuc.Item2) IdSucursal = ObjUsuario.Id_sucursal;
				else IdSucursal = Convert.ToInt32(ddlSucursal.SelectedValue);
				phInformacion.Visible = true;
				phTrabajdor.Visible = true;
				Listas.Trabajadores_Puestos(ddlTrabajador, Convert.ToInt32(ddlPuesto.SelectedValue));
			}
			else
			{
				ViewState["puesto"] = "0";
			}
		}
		#endregion

	}
}