//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MsjAsync", ReplyAction="http://tempuri.org/IService1/MsjAsyncResponse")]
        string MsjAsync();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/MsjAsync", ReplyAction="http://tempuri.org/IService1/MsjAsyncResponse")]
        System.IAsyncResult BeginMsjAsync(System.AsyncCallback callback, object asyncState);
        
        string EndMsjAsync(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_Riesgos_Default", ReplyAction="http://tempuri.org/IService1/add_Riesgos_DefaultResponse")]
        bool add_Riesgos_Default(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/add_Riesgos_Default", ReplyAction="http://tempuri.org/IService1/add_Riesgos_DefaultResponse")]
        System.IAsyncResult Beginadd_Riesgos_Default(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState);
        
        bool Endadd_Riesgos_Default(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_NormasSucursal", ReplyAction="http://tempuri.org/IService1/add_NormasSucursalResponse")]
        bool add_NormasSucursal(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/add_NormasSucursal", ReplyAction="http://tempuri.org/IService1/add_NormasSucursalResponse")]
        System.IAsyncResult Beginadd_NormasSucursal(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState);
        
        bool Endadd_NormasSucursal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add_MedidasSucursal", ReplyAction="http://tempuri.org/IService1/add_MedidasSucursalResponse")]
        bool add_MedidasSucursal(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/add_MedidasSucursal", ReplyAction="http://tempuri.org/IService1/add_MedidasSucursalResponse")]
        System.IAsyncResult Beginadd_MedidasSucursal(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState);
        
        bool Endadd_MedidasSucursal(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        CapaServ.CompositeType GetDataUsingDataContract(CapaServ.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(CapaServ.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        CapaServ.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SGSST.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsjAsyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MsjAsyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class add_Riesgos_DefaultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public add_Riesgos_DefaultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class add_NormasSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public add_NormasSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class add_MedidasSucursalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public add_MedidasSucursalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CapaServ.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CapaServ.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SGSST.ServiceReference1.IService1>, SGSST.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginMsjAsyncDelegate;
        
        private EndOperationDelegate onEndMsjAsyncDelegate;
        
        private System.Threading.SendOrPostCallback onMsjAsyncCompletedDelegate;
        
        private BeginOperationDelegate onBeginadd_Riesgos_DefaultDelegate;
        
        private EndOperationDelegate onEndadd_Riesgos_DefaultDelegate;
        
        private System.Threading.SendOrPostCallback onadd_Riesgos_DefaultCompletedDelegate;
        
        private BeginOperationDelegate onBeginadd_NormasSucursalDelegate;
        
        private EndOperationDelegate onEndadd_NormasSucursalDelegate;
        
        private System.Threading.SendOrPostCallback onadd_NormasSucursalCompletedDelegate;
        
        private BeginOperationDelegate onBeginadd_MedidasSucursalDelegate;
        
        private EndOperationDelegate onEndadd_MedidasSucursalDelegate;
        
        private System.Threading.SendOrPostCallback onadd_MedidasSucursalCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<MsjAsyncCompletedEventArgs> MsjAsyncCompleted;
        
        public event System.EventHandler<add_Riesgos_DefaultCompletedEventArgs> add_Riesgos_DefaultCompleted;
        
        public event System.EventHandler<add_NormasSucursalCompletedEventArgs> add_NormasSucursalCompleted;
        
        public event System.EventHandler<add_MedidasSucursalCompletedEventArgs> add_MedidasSucursalCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return this.BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public string MsjAsync() {
            return base.Channel.MsjAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginMsjAsync(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMsjAsync(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndMsjAsync(System.IAsyncResult result) {
            return base.Channel.EndMsjAsync(result);
        }
        
        private System.IAsyncResult OnBeginMsjAsync(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginMsjAsync(callback, asyncState);
        }
        
        private object[] OnEndMsjAsync(System.IAsyncResult result) {
            string retVal = this.EndMsjAsync(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMsjAsyncCompleted(object state) {
            if ((this.MsjAsyncCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MsjAsyncCompleted(this, new MsjAsyncCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MsjAsyncAsync() {
            this.MsjAsyncAsync(null);
        }
        
        public void MsjAsyncAsync(object userState) {
            if ((this.onBeginMsjAsyncDelegate == null)) {
                this.onBeginMsjAsyncDelegate = new BeginOperationDelegate(this.OnBeginMsjAsync);
            }
            if ((this.onEndMsjAsyncDelegate == null)) {
                this.onEndMsjAsyncDelegate = new EndOperationDelegate(this.OnEndMsjAsync);
            }
            if ((this.onMsjAsyncCompletedDelegate == null)) {
                this.onMsjAsyncCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMsjAsyncCompleted);
            }
            base.InvokeAsync(this.onBeginMsjAsyncDelegate, null, this.onEndMsjAsyncDelegate, this.onMsjAsyncCompletedDelegate, userState);
        }
        
        public bool add_Riesgos_Default(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            return base.Channel.add_Riesgos_Default(act1, act2, act3, id_sucursal, ObjUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginadd_Riesgos_Default(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginadd_Riesgos_Default(act1, act2, act3, id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endadd_Riesgos_Default(System.IAsyncResult result) {
            return base.Channel.Endadd_Riesgos_Default(result);
        }
        
        private System.IAsyncResult OnBeginadd_Riesgos_Default(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string act1 = ((string)(inValues[0]));
            string act2 = ((string)(inValues[1]));
            string act3 = ((string)(inValues[2]));
            string id_sucursal = ((string)(inValues[3]));
            Capa_Datos.Model_UsuarioSistema ObjUsuario = ((Capa_Datos.Model_UsuarioSistema)(inValues[4]));
            return this.Beginadd_Riesgos_Default(act1, act2, act3, id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        private object[] OnEndadd_Riesgos_Default(System.IAsyncResult result) {
            bool retVal = this.Endadd_Riesgos_Default(result);
            return new object[] {
                    retVal};
        }
        
        private void Onadd_Riesgos_DefaultCompleted(object state) {
            if ((this.add_Riesgos_DefaultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.add_Riesgos_DefaultCompleted(this, new add_Riesgos_DefaultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void add_Riesgos_DefaultAsync(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            this.add_Riesgos_DefaultAsync(act1, act2, act3, id_sucursal, ObjUsuario, null);
        }
        
        public void add_Riesgos_DefaultAsync(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, object userState) {
            if ((this.onBeginadd_Riesgos_DefaultDelegate == null)) {
                this.onBeginadd_Riesgos_DefaultDelegate = new BeginOperationDelegate(this.OnBeginadd_Riesgos_Default);
            }
            if ((this.onEndadd_Riesgos_DefaultDelegate == null)) {
                this.onEndadd_Riesgos_DefaultDelegate = new EndOperationDelegate(this.OnEndadd_Riesgos_Default);
            }
            if ((this.onadd_Riesgos_DefaultCompletedDelegate == null)) {
                this.onadd_Riesgos_DefaultCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onadd_Riesgos_DefaultCompleted);
            }
            base.InvokeAsync(this.onBeginadd_Riesgos_DefaultDelegate, new object[] {
                        act1,
                        act2,
                        act3,
                        id_sucursal,
                        ObjUsuario}, this.onEndadd_Riesgos_DefaultDelegate, this.onadd_Riesgos_DefaultCompletedDelegate, userState);
        }
        
        public bool add_NormasSucursal(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            return base.Channel.add_NormasSucursal(act1, act2, act3, id_sucursal, ObjUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginadd_NormasSucursal(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginadd_NormasSucursal(act1, act2, act3, id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endadd_NormasSucursal(System.IAsyncResult result) {
            return base.Channel.Endadd_NormasSucursal(result);
        }
        
        private System.IAsyncResult OnBeginadd_NormasSucursal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string act1 = ((string)(inValues[0]));
            string act2 = ((string)(inValues[1]));
            string act3 = ((string)(inValues[2]));
            string id_sucursal = ((string)(inValues[3]));
            Capa_Datos.Model_UsuarioSistema ObjUsuario = ((Capa_Datos.Model_UsuarioSistema)(inValues[4]));
            return this.Beginadd_NormasSucursal(act1, act2, act3, id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        private object[] OnEndadd_NormasSucursal(System.IAsyncResult result) {
            bool retVal = this.Endadd_NormasSucursal(result);
            return new object[] {
                    retVal};
        }
        
        private void Onadd_NormasSucursalCompleted(object state) {
            if ((this.add_NormasSucursalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.add_NormasSucursalCompleted(this, new add_NormasSucursalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void add_NormasSucursalAsync(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            this.add_NormasSucursalAsync(act1, act2, act3, id_sucursal, ObjUsuario, null);
        }
        
        public void add_NormasSucursalAsync(string act1, string act2, string act3, string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, object userState) {
            if ((this.onBeginadd_NormasSucursalDelegate == null)) {
                this.onBeginadd_NormasSucursalDelegate = new BeginOperationDelegate(this.OnBeginadd_NormasSucursal);
            }
            if ((this.onEndadd_NormasSucursalDelegate == null)) {
                this.onEndadd_NormasSucursalDelegate = new EndOperationDelegate(this.OnEndadd_NormasSucursal);
            }
            if ((this.onadd_NormasSucursalCompletedDelegate == null)) {
                this.onadd_NormasSucursalCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onadd_NormasSucursalCompleted);
            }
            base.InvokeAsync(this.onBeginadd_NormasSucursalDelegate, new object[] {
                        act1,
                        act2,
                        act3,
                        id_sucursal,
                        ObjUsuario}, this.onEndadd_NormasSucursalDelegate, this.onadd_NormasSucursalCompletedDelegate, userState);
        }
        
        public bool add_MedidasSucursal(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            return base.Channel.add_MedidasSucursal(id_sucursal, ObjUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginadd_MedidasSucursal(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginadd_MedidasSucursal(id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endadd_MedidasSucursal(System.IAsyncResult result) {
            return base.Channel.Endadd_MedidasSucursal(result);
        }
        
        private System.IAsyncResult OnBeginadd_MedidasSucursal(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id_sucursal = ((string)(inValues[0]));
            Capa_Datos.Model_UsuarioSistema ObjUsuario = ((Capa_Datos.Model_UsuarioSistema)(inValues[1]));
            return this.Beginadd_MedidasSucursal(id_sucursal, ObjUsuario, callback, asyncState);
        }
        
        private object[] OnEndadd_MedidasSucursal(System.IAsyncResult result) {
            bool retVal = this.Endadd_MedidasSucursal(result);
            return new object[] {
                    retVal};
        }
        
        private void Onadd_MedidasSucursalCompleted(object state) {
            if ((this.add_MedidasSucursalCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.add_MedidasSucursalCompleted(this, new add_MedidasSucursalCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void add_MedidasSucursalAsync(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario) {
            this.add_MedidasSucursalAsync(id_sucursal, ObjUsuario, null);
        }
        
        public void add_MedidasSucursalAsync(string id_sucursal, Capa_Datos.Model_UsuarioSistema ObjUsuario, object userState) {
            if ((this.onBeginadd_MedidasSucursalDelegate == null)) {
                this.onBeginadd_MedidasSucursalDelegate = new BeginOperationDelegate(this.OnBeginadd_MedidasSucursal);
            }
            if ((this.onEndadd_MedidasSucursalDelegate == null)) {
                this.onEndadd_MedidasSucursalDelegate = new EndOperationDelegate(this.OnEndadd_MedidasSucursal);
            }
            if ((this.onadd_MedidasSucursalCompletedDelegate == null)) {
                this.onadd_MedidasSucursalCompletedDelegate = new System.Threading.SendOrPostCallback(this.Onadd_MedidasSucursalCompleted);
            }
            base.InvokeAsync(this.onBeginadd_MedidasSucursalDelegate, new object[] {
                        id_sucursal,
                        ObjUsuario}, this.onEndadd_MedidasSucursalDelegate, this.onadd_MedidasSucursalCompletedDelegate, userState);
        }
        
        public CapaServ.CompositeType GetDataUsingDataContract(CapaServ.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(CapaServ.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public CapaServ.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CapaServ.CompositeType composite = ((CapaServ.CompositeType)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            CapaServ.CompositeType retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(CapaServ.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(CapaServ.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
    }
}
